BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB BBBB

BBBBB BBBBB gettext(u'Contact RWM EL') BBBBBBBB
BBBBB BBBBBBBBBBXXXXXXXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX gettext(u'Contact RWM EL') XXXXX
      XX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Clear communication is where safe electrical work begins.') SSSSS SSSSSSSSSSSSS SS SSSSS SSSS SSSSSSSSSS SSSS SSSSSSSXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BXX gettext(u'Book an Electrician') XXXX
        XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Book Consultation') XXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXXX

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Inquiry Types') XXXXXX
      XXXX gettext(u'How Can We Help You?') XXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXX gettext(u'New service bookings') XXXXXXX
      XXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXX gettext(u'Professional consultations') XXXXXXX
      XXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXX gettext(u'Technical questions &amp; support') XXXXXXX
      XXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX gettext(u'Phone') XXXXX
        XXX gettext(u'Speak with our expert dispatch team for immediate assistance.') XXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXX XXXXXXXXX
      XXXXXXXXXX
      XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX gettext(u'Email') XXXXX
        XXX gettext(u'Send us project plans or detailed inquiries for a formal quote.') XXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXX
      XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX gettext(u'Contact Form') XXXXX
        XXX gettext(u'Quickly submit your details and we will respond within 24 hours.') XXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Submit Inquiry') XXXXXXX
      XXXXXXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXXX

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX gettext(u'Start Your Project Journey') XXXXX
      XXX gettext(u'Our certified engineers are ready to assist with residential, commercial, and industrial electrical needs across Sweden.') XXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXX
          XXXX gettext(u'Operating Hours') XXXXX
          XXX gettext(u'Mon - Fri آ· 07:00 - 17:00') XXXX
        XXXXXX
        XXXXX
          XXXX gettext(u'Headquarters') XXXXX
          XXX gettext(u'Stockholm Business Park, Sweden') XXXX
        XXXXXX
      XXXXXX
    XXXXXX
    XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBXX
      BBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX gettext(u'Full Name') 
          XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'John Doe') X XXXXXXXXX
        XXXXXXXX
        XXXXXXX gettext(u'Email Address') 
          XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'john@example.com') X XXXXXXXXX
        XXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX gettext(u'Phone Number') 
          XXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XX XXX XX XXXX
        XXXXXXXX
        XXXXXXX gettext(u'Project Address') 
          XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Street name, City') XX
        XXXXXXXX
      XXXXXX
      XXXXXXX gettext(u'Type of Request') 
        XXXXXXX XXXXXXXXXXXXXXXXXXXX
          XXXXXXXX gettext(u'Residential Electrical Service') XXXXXXXXX
          XXXXXXXX gettext(u'Commercial Installation') XXXXXXXXX
          XXXXXXXX gettext(u'Emergency Support') XXXXXXXXX
          XXXXXXXX gettext(u'Smart Home Consultation') XXXXXXXXX
        XXXXXXXXX
      XXXXXXXX
      XXXXXXX gettext(u'Your Message') 
        XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Tell us more about your needs...') X XXXXXXXXXXXXXXXXXXXX
      XXXXXXXX
      XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Send Message') XXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX
         gettext(u'I consent to the processing of my personal data for the purpose of this inquiry in accordance with GDPR regulations.') 
      XXXXXXXX
      BB BBBBBBBBBBBBBB BB BBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Thank you! We have received your request.') XXXXXX
      BBBB BBBBBBBBBBBBBB BB BBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'We could not send your message right now. Please try again.') XXXXXX
      BBBBB
      XXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Encrypted and secure communication') XXXXXX
    XXXXXXX
  XXXXXX
XXXXXXXXXX

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX gettext(u'What Happens After You Contact Us?') XXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX
        XXXX gettext(u'Review') XXXXX
        XXX gettext(u'Our technical lead reviews your request to assign the most suitable specialist.') XXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX
        XXXX gettext(u'Discovery Call') XXXXX
        XXX gettext(u'We reach out to clarify details, discuss your timeline, and provide initial insights.') XXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX
        XXXX gettext(u'Proposal') XXXXX
        XXX gettext(u'You receive a clear, transparent project proposal and a direct booking link.') XXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXXX

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX gettext(u'Not sure where to start?') XXXXX
    XXX gettext(u"We're here to guide you.") XXXX
    XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Book Consultation') XXXX
  XXXXXX
XXXXXXXXXX
BBBBBBBB
