XBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBBB BBBB

BBBBB BBBBBBBBBBXXXXX XXXXXXXXXBBBBBBBB
BBBBB BBBBBBBBBBBBBXXXXXXX XXXXXX XXX XXXXXXXXX XXXXXXXXX XXX XXXXXXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXX
                XXXXX XXXXX XXXXXXXX X X XXX X XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXX
                XXXXX XXXXX XXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXX XXXXXX X X X X X XXXXXXXXXXXXX X X X XXXXXXXXX X X X X XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXX
                XXXXX XXXXX XXXXXX XXXXX XXXXXX XXXXXX X X X X X XXXXX X X X XXX XXXXX X X X XXXXXXXXX X X X X XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXX
                XXXXX XXXXX XXXXXXXXX XXXXXX XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXX
                XXXXX XXXXXX XXXXX XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXX XXXX X X X X XX XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXX
                XXXXX XXXXXX XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXX
                XXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXX XXXXX XXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXX
                XXXXX XXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXX XXX XXXX XXXX XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXX
                XXXXX XXXXX XXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXX XXXXXX XXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXX XXXXX XXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXX XXXXXX XXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXXX

XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXX
            XXXXXXXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXX XXXXXX XXXXXXX XX XXXX XXXXXXXXXXXXXX
        XXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX
            XXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXX
                XXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXX XXX XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFXXXXXXX XXXXXXXXXXXX
            XXXXXX
        XXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
            BBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXX XXXXXXX XXXXXX XXX XXX XXXXX XXXXXXXXXXXXX
                XXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XX XXXX XXXX XXXXXXX XXXXXXXXXXXXX XXXX XXX XXXXXX XXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXXX
    XXXXXX
XXXXXXXXXX

XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXX
            XXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX
        XXXXXX
        BBB BBBBBBB BB BBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXX
                XXXXXXFFFFFFF FF FFFFXXXXXXX
                XXXXXXXXXXXXX
                XXXXXXFFFFFFFFFFFXXXXXXX
                XXXXXXFFFFFFFFFFFXXXXXXX
                XXXXXXFFFFFFF FF FFFFFFFFFFFFFXXXXXXX
                XXXXXXXXXXXXX
            XXXXXX
        BBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX
        BBBBBB
    XXXXXX
XXXXXXXXXX

XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXX
            XXXXXXXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXX XXXXXXXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXX XXXXXXX
        XX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXX
        XX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXX
        XX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXX XXXXXXXXXXX
        XX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXX XXXXXXXXXXX
        XX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXX XXXXXXXXXXX
        XX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXX XXXXXXXXXXX
        XX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXX XXXXXXXXXXX
        XX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXX
        XX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXX XXXXXXXXXX
    XXXXXX
XXXXXXXXXX

XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    BBB BBBB BB BBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXX
                    XXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBB
                        XX XXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBXXXXXXXXXXXX
                    BBBBB
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    BBB BBBBB BB BBBBBBBBBBB
                        XXXXXXFFFFFXXXXXXX
                    BBBBBB
                XXXXXX
                BBB BBB BB BBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXX
                        BBB BBBBB BB BBBBBBBBBBB
                            XXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXXXXX
                        BBBBBB
                    XXXXXX
                BBBBB
                    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX
                BBBBBB
            XXXXXX
        XXXXXX
    BBBBBB
XXXXXXXXXX

XXXXXXXX
    XXXXXXXXX XX X
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXXXX XXXXXXXXXXXXXXXXXXX X
            XX XXXXXXX XX XXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXXX X XXXXXX
            XXXXXXXXXXXXXXXXXXXXXX X XXXXXX
            XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X XXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X XXX
        X

        XXXXXXXX XXXXXXXXXXXXXXXXXXX X
            XX XXXXXXXXXXXXXXXXX XX XXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXX
        X

        XX XXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        X

        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
            XX XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX X XXXXXXXXX X XXXXXXXXXXX
        X

        XX XXXXXXXXXXXXXXX X
            XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXX
            XXXXXXXXXXXXXXXXXXXXX X XXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
            XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

            XX XXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX
            X

            XX XXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXX X
                        XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXX
                        XXXXXXXXXXXXXXXXXXXXX X XXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    X
                XXX
            X

            XX XXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
                    XX XXXXXXXXXXXXXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X XXXXXX X XXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX
            X
        XXX

        XX XXXXXXXX XX XXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
                XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX X XXXXXX X XXXXXXXXX
            XXX

            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XX X
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                XXXXX XXXXXX X XXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXX
        X

        XX XXXXXXX X
            XXXXX XXXXXX X X
                XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX

            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
                    XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                        XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX
                        XXXXXXX
                    X
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX XXXXXXX X
                        XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX
                        XXXXXXX
                    X
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                        XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXX
                        XXXXXXX
                    X
                    XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX
                XXX
            XXX
        X

        XXXXX XXXXXXXX XXXXXX X
            XXX X
                XXXXX XXX X XXXXX XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX X XXXXXXXXXXXX XXXXXXXXXXXXX XXX
                XX XXXXXXXXX XXXXXXX
                XXXXX XXXX X XXXXX XXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX

                XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX
                XXXXX XXXXXX X XXXXXXXXXX XX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX X XXXXX
                XX XXXXXXX XX XXXXXXXXX X XXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXX XX XXXXXX XX XXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX X
                        XXX XXXXXXXXXXXXXXXXXXX XXXXXXX X XXXXX XXXXXXXXXXXXXX XXX
                    X
                X
            X XXXXX XXX XX
        X

        XXXXXXX
        XXXXXXXXXXXXXXXXX XXXXXXX
    XXXXX
XXXXXXXXX
BBBBBBBB
