XBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'FAQ | RWM EL') BBBBBBBB
BBBBB BBBBBBBBBBXXXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX gettext(u'FAQ') XXXXXX
    XXXX gettext(u'Frequently Asked Questions') XXXXX
    XXX gettext(u'Clear answers to the most common questions about bookings, pricing, and services.') XXXX
  XXXXXX
XXXXXXXXXX

XXXXXXXX XXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      BBB BBB BB BBBB
        XXXXXXXX XXXXXXXXXXXXXXXXX
          XXXXXXXXX
            XXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            FFFFFFFFFFFF
          XXXXXX
        XXXXXXXXXX
      BBBBB
        XXXX XXXXXXXXXXXXXXXXXX gettext(u'No FAQ entries yet. Please check back soon.') XXXXXX
      BBBBBB
    XXXXXX
  XXXXXX
XXXXXXXXXX
BBBBBBBB
