BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB BBBB

BBBBB BBBBB gettext(u'Privacy Policy | RWM EL Pro Edition') BBBBBBBB
BBBBB BBBBBBBBBBXXXXXXXXXXXXBBBBBBBB

BBBBB BBBBBBBBBB
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX X X
      XXXXXXXXX XXXXXXXX
      XXXXXX X
        XXXXXXX X
          XXXXXXX X
            XXXXXXXXXX XXXXXXXXXX
            XXXXXXXXXXXX XXXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXXXX
            XXXXXXXXXXXX XXXXXXXXX
          XX
          XXXXXXXXXXX X
            XXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXX
            XXXXXXX XXXXXXXXX XXXXXXXXXXXXX
          X
        X
      X
    X
  XXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXX X
      XXXX X
        XXXXXXXXXXXXXXXX XXXXXXX
      X
      XXXX X
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX
      X
      XXX XXX XXX XX X
        XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
      X
      XXXXXXXXX X
        XXXXXX XXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      X
      XXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
      X
      XXXXXXXXXXXXXXX X
        XXXXXX XXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
      X
      XXXXXXXXXXXXXXX X
        XXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXX XXXXXX
      X
      XXXXXXXXXXX X
        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXX
      X
      XXXXXXXXXXX X
        XXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      X
    X
  XXXXXXXX
  XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXX XXXXXXXX
      XXXXXX XXXXXXXX
      XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
    X
  XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXX XXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXX gettext(u'Transparency & Security') XXXXXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Privacy Policy') XXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX gettext(u'Effective Date: 30 January 2026') XXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX
         gettext(u'At RWM EL, we believe data protection is a fundamental pillar of professional service. This policy details our commitment to your privacy under Swedish and EU regulations.') 
      XXXX
    XXXXXX
  XXXXXX
XXXXXXXXXX

XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXX XXXXXXXXXXX XXXX XXXXX XXXXXXXX
  XXXXXX XXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXX
    XXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXX gettext(u'Contents') XXXXX
      XXXX XXXXXXXXXXX XXXXXXXX XXXXXXX
        XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'01. Data Controller') XXXX
        XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'02. Scope of Policy') XXXX
        XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'03. Data Sources') XXXX
        XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'04. Data Collection') XXXX
        XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'05. Purpose') XXXX
        XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'06. Legal Basis') XXXX
        XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'07. Data Retention') XXXX
        XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'08. Data Security') XXXX
        XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'09. Data Sharing') XXXX
        XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'10. Int. Transfers') XXXX
        XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'11. Your GDPR Rights') XXXX
        XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'12. Cookies') XXXX
        XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'13. On-Site Protocol') XXXX
        XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'14. Marketing') XXXX
        XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'15. Automation') XXXX
        XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u"16. Children's Privacy") XXXX
        XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'17. Policy Updates') XXXX
        XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'18. Complaints') XXXX
      XXXXXX
    XXXXXX
  XXXXXXXX
  XXXXX XXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXX gettext(u'Data Controller') XXXXX
      XXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXX gettext(u'RWM EL is the designated data controller for all processing activities described herein. We are a registered Swedish electrical service provider operating with full technical compliance.') XXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXX XXXXXX gettext(u'Email Enquiries') XXXXXXX
            XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXX XXXXXX gettext(u'Direct Line') XXXXXXX
            XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX XX XXX XX XXXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXXXXXX

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXX gettext(u'Scope of Policy') XXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'This policy applies to all customers, website visitors, and partners of RWM EL. It covers data collected via our website, on-site electrical service visits, telephone inquiries, and digital communications.') XXXX
    XXXXXXXXXX

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXX gettext(u'Sources of Personal Data') XXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
          XXXXX
            XXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXX gettext(u'Direct Interaction') XXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Information provided when you request a quote or book a service.') XXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
          XXXXX
            XXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXX gettext(u'Automated Systems') XXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Data collected through cookies and website analytics.') XXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
          XXXXX
            XXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXX gettext(u'Public Registries') XXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Verified data from SPAR for Swedish tax (ROT) eligibility.') XXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXXXXXX

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXX gettext(u'Personal Data We Collect') XXXXX
      XXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
        XXX XXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXX
          XXXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Identity & Swedish PIN (for ROT)') XXXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXX
          XXXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Contact & Property Address') XXXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXX
          XXXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Technical Installation Specs') XXXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXX
          XXXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Billing & Payment History') XXXXXXX
        XXXXX
      XXXXX
    XXXXXXXXXX

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXX gettext(u'Purpose of Processing') XXXXX
      XXXX XXXXXXXXXXXXXXXXX XXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
          XXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
          XXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'ROT & Legal Disclosures') XXXXX
          XXXXXX
        XXXXXX
        XX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXX
           gettext(u'For Swedish residential customers, we are legally required to collect your Personal Identity Number (personnummer) to facilitate the ROT tax deduction. This data is transmitted securely to the Swedish Tax Agency (Skatteverket).') 
        XXXX
        XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Required Action') 
          XXXX
          XX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXX gettext(u'Failure to provide this information may result in the full invoice amount being charged without the tax benefit.') XXXX
        XXXXXX
      XXXXXX
      XX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Beyond tax compliance, data is used for service execution, scheduling, safety certification, and mandatory bookkeeping under the Swedish Bookkeeping Act.') XXXX
    XXXXXXXXXX

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXX gettext(u'Legal Basis for Processing') XXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
        XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXX XXXXXX gettext(u'Contract') XXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Fulfilling our service agreement with you.') XXXX
        XXXXXX
        XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXX XXXXXX gettext(u'Legal Obligation') XXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Adhering to tax laws and safety regulations.') XXXX
        XXXXXX
        XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXX XXXXXX gettext(u'Interest') XXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Improving site performance and security.') XXXX
        XXXXXX
      XXXXXX
    XXXXXXXXXX

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXX gettext(u'Data Retention') XXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'We store your data only as long as necessary. Service records are kept for <span class="font-bold text-navy-deep">10 years</span> to comply with technical warranty periods and Swedish bookkeeping laws.') SS SSSSS SSSS SSSS SSSS SS SSSS SS SSSSSSSSSS SSSSSSS SSSSSSS SSS SSSS SSS SSSSS SSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSS SSSSSSSSSSSS SS SSSSSS SSSS SSSSSSSSS SSSSSSSS SSSSSSS SSS SSSSSSS SSSSSSSSSSS SSSSSXXXX
    XXXXXXXXXX

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXX gettext(u'Data Security') XXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'We implement high-tier technical and organizational measures, including AES-256 encrypted servers and strict limited-access protocols, to protect your data against unauthorized access or loss.') XXXX
    XXXXXXXXXX

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXX gettext(u'Sharing with Third Parties') XXXXX
      XX XXXXXXXXXXXXX gettext(u'We never sell your data. We only share with:') XXXX
      XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXX
        XXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Specialist Subcontractors') XXXXXXX
        XXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Billing Platforms') XXXXXXX
        XXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'IT Infrastructure') XXXXXXX
      XXXXXX
    XXXXXXXXXX

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXX gettext(u'International Transfers') XXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'RWM EL primarily processes data within the EU/EEA. If data is transferred outside this zone, we ensure Standard Contractual Clauses (SCCs) are in place to maintain GDPR levels of protection.') XXXX
    XXXXXXXXXX

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX gettext(u'Your GDPR Rights') XXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
            XXX XXXXXXXXXXXXXXXX XXXXXX gettext(u'Right to Access') XXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Request a full extract of all personal data we hold about you.') XXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
            XXX XXXXXXXXXXXXXXXX XXXXXX gettext(u'Right to Rectification') XXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Demand the correction of inaccurate or incomplete information.') XXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
            XXX XXXXXXXXXXXXXXXX XXXXXX gettext(u'Right to Erasure') XXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Request deletion where data is no longer necessary for legal reasons.') XXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
            XXX XXXXXXXXXXXXXXXX XXXXXX gettext(u'Data Portability') XXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Receive your data in a structured, machine-readable format.') XXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
            XXX XXXXXXXXXXXXXXXX XXXXXX gettext(u'Right to Object') XXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Object to data processing based on our legitimate interests.') XXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
            XXX XXXXXXXXXXXXXXXX XXXXXX gettext(u'Restriction') XXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Request the limitation of how we process your personal data.') XXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXXXXXX

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXX gettext(u'Cookies and Tracking') XXXXX
      BBB BBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'We use technical and analytical cookies to optimize website performance. For detailed information, please refer to our dedicated <a class="text-primary font-bold hover:underline" href="%(url)s">Cookie Policy</a>.') SS SSS SSSSSSSSS SSS SSSSSSSSSS SSSSSSS SS SSSSSSSS SSSSSSS SSSSSSSSSSSS SSS SSSSSSSS SSSSSSSSSSSS SSSSSS SSSSS SS SSS SSSSSSSSS SS SSSSSSSSSSSSSSSSSSS SSSSSSSSS SSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSSS SSSSSSSSSSSXXXX
    XXXXXXXXXX

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXX gettext(u'On-Site Service Protocols') XXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'During physical site visits, our electricians may document technical installations with photographs. These are used solely for technical documentation, safety audits, and quality assurance.') XXXX
    XXXXXXXXXX

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXX gettext(u'Marketing Communications') XXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'You will only receive marketing emails if you have explicitly opted in. You can unsubscribe at any time via the link provided in every communication.') XXXX
    XXXXXXXXXX

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXX gettext(u'Automated Decision Making') XXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'RWM EL does not use automated decision-making or profiling systems that produce legal effects concerning you.') XXXX
    XXXXXXXXXX

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXX gettext(u"Children's Privacy") XXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Our services are designed for property owners and businesses. We do not knowingly collect or process data from individuals under the age of 18.') XXXX
    XXXXXXXXXX

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXX gettext(u'Policy Updates') XXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'We periodically update this policy to reflect changes in our technical practices or legal requirements. Updates are effective immediately upon posting.') XXXX
    XXXXXXXXXX

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXX gettext(u'Complaints') XXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX gettext(u'If you believe we have mishandled your data, you have the right to lodge a complaint with the Swedish Authority for Privacy Protection (Integritetsskyddsmyndigheten - IMY).') XXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXXXX
         gettext(u'Visit IMY.se') 
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXXXXXX
  XXXXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBBBB
  XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
      XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXX XXXXXXXXXXXXXXXXXX X
        XXX XXXXX X XXXXXXXXXXXXXXXX
        XXXXX XXXXXXXX XX XXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXXXXXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      X
      XXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXX
  XXXXXXXXX
BBBBBBBB
