BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB BBBB

BBBBB BBBBB gettext(u'Customer Support | Hembla experten') BBBBBBBB
BBBBB BBBBBBBBBBXXXXXXXXXXXXBBBBBBBB

BBBBB BBBBBBBBBB
  XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
BBBBBBBB

BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX gettext(u'Customer Support') XXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Clear answers. Responsible support.') XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX gettext(u'View FAQs') XXXX
        XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Submit Ticket') XXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXXX

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'What We Can Help You With') XXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX gettext(u'Ongoing Work') XXXXX
        XXX gettext(u'Real-time updates on your current electrical installation. Monitor progress and scheduled inspections in real-time.') XXXX
      XXXXXXXXXX
      XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX gettext(u'Follow-ups') XXXXX
        XXX gettext(u'Quality checks and premium maintenance support after project completion. We ensure long-term system integrity.') XXXX
      XXXXXXXXXX
      XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX gettext(u'Documentation') XXXXX
        XXX gettext(u'Direct access to your safety certificates, warranties, and technical drawings in our secure client portal.') XXXX
      XXXXXXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXXX

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Premium Contact Channels') XXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX gettext(u'Priority Line') XXXXX
        XXXXXX X XXX XXX XXXXXX
        XXXXXX gettext(u'Mon - Fri 08:00 - 17:00') XXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX gettext(u'Concierge Email') XXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX gettext(u'24-hour response guarantee') XXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX gettext(u'Digital Portal') XXXXX
        XXX gettext(u'Open Support Ticket') XXXX
        XXXXXX gettext(u'Trackable request system') XXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXXX

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Direct Support Form') XXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Submit your detailed request and our technical team will review it within 2 business hours.') XXXX

    BB BBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
         gettext(u'Ticket received. Your reference ID is')  XXXXXXXXXXXXXXXXXX
      XXXXXX
    BBBBB

    BB BBBBBB
      XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXX
          BBB BBBBB BB BBBBBB
            XXXXXXXXX
          BBBBBB
        XXXXX
      XXXXXX
    BBBBB

    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
      BBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXX
        XXXXX
          XXXXXXX gettext(u'Full Name') XXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFFXX
        XXXXXX
        XXXXX
          XXXXXXX gettext(u'Email Address') XXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXFFFFFFFFFFXX
        XXXXXX
        XXXXX
          XXXXXXX gettext(u'Phone Number') XXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXFFFFFFFFFFXX
        XXXXXX
        XXXXX
          XXXXXXX gettext(u'Type of Request') XXXXXXXX
          XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXX gettext(u'Select') XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXXXBBBBBX gettext(u'Technical Issue') XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBB BB BBBBBBBBBXXXXXXXXBBBBBX gettext(u'Billing') XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBXXXXXXXXBBBBBX gettext(u'Maintenance') XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBXXXXXXXXBBBBBX gettext(u'Documentation') XXXXXXXXX
          XXXXXXXXX
        XXXXXX
        XXXXX
          XXXXXXX gettext(u'Customer Type') XXXXXXXX
          XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXX gettext(u'Select') XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBXXXXXXXXBBBBBX gettext(u'Residential Client') XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBBXXXXXXXXBBBBBX gettext(u'Business Client') XXXXXXXXX
            XXXXXXX XXXXXXXXXXX BB BBBBBBBBBBBBBBBBBB BB BBBBBXXXXXXXXBBBBBX gettext(u'Housing Association') XXXXXXXXX
          XXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXX
          XXXXXXX gettext(u'Project Address') XXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFFXX
        XXXXXX
        XXXX XXXXXXXXXXXXX
          XXXXXXX gettext(u'Message') XXXXXXXX
          XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXFFFFFFFFFFXXXXXXXXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX gettext(u'Submit Request') XXXXXXXXX
      XXXXXX
    XXXXXXX
  XXXXXX
XXXXXXXXXX

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'What Happens Next') XXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX gettext(u'Request Logged') XXXXX
        XXX gettext(u'Our system instantly assigns a ticket number and notifies our technical lead.') XXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX gettext(u'Expert Review') XXXXX
        XXX gettext(u'A certified electrician reviews your request to prepare the best solution.') XXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX gettext(u'Active Support') XXXXX
        XXX gettext(u'You receive a direct response or site visit confirmation within the promised timeframe.') XXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXXX
BBBBBBBB
