BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB BBBB

BBBBB BBBBB gettext(u'Service Booking') BBBBBBBB
BBBBB BBBBBBBBBBXXXXXXXXXXXXXXXXXXXXBBBBBBBB

BBBBB BBBBBBBBBB
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
BBBBBBBB

BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      BB BBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      BBBBB
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Step %(step)s of 12: %(subtitle)s') SSSS SSSSSSSS SS SSS SSSSSSSSSSSSXXXXXX
          BB BBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          BBBBB
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'%(progress)s%% Complete') SSSSSSSSSSSSSS SSSSSSSSXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
      BB BBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXX gettext(u'Please fix the following:') XXXXXXXXX
          XXXX
            BBB BBB BB BBBBBB
              XXXXXXXXX
            BBBBBB
          XXXXX
        XXXXXX
      BBBBB
      XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
      BB BBBBBBBBBBB
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      BBBBB
      BBBBB BBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
  XXXXXX
XXXXXXXXXX

BBBBB BBBBBBBB
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
BBBBBBBB
BBBBBBBB
