XBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
  BBBBBBBBBB

  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Billing & Documentation') 
        XXXXXX

        XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
           gettext(u'Please provide your billing identity, property details, and any helpful files to finalize your request.') 
        XXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
           gettext(u'Save Draft') 
        XXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
           gettext(u'Next Step') 
        XXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       gettext(u'Billing Identity') 
      XXXXX XXXXXXXXXXXXXXXXXX gettext(u'GDPR Compliant') XXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBB BB BBBBBBBBBXXXXXXXBBBBB XXXXXXXXX
        XXXXXX gettext(u'Private (Personal ID)') XXXXXXX
      XXXXXXXX

      XXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBXXXXXXXBBBBBX
        XXXXXX gettext(u'Business (Org Number)') XXXXXXX
      XXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX
           gettext(u'Personal Identity Number (SSN)') 
          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXX gettext(u'YYYYMMDD-XXXX') X
                 XXXXXXXFFFFFFFFFFX
                 XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXX
             gettext(u'Standard Swedish format for tax and insurance purposes.') 
          XXXXXXX
        XXXXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX
           gettext(u'Full Legal Name') 
          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXX gettext(u'As it appears on ID') X
                 XXXXXXXFFFFFFFFFFX
                 XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX
           gettext(u'Company Name') 
          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXX gettext(u'Registered company name') X
                 XXXXXXXFFFFFFFFFFX
                 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX
           gettext(u'Organization Number') 
          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXXXXXXXXXXXXX
                 XXXXXXXFFFFFFFFFFX
                 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX
      XXXXXX

    XXXXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXX XXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BXX
       gettext(u'Back') 
    XXXX
    XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
       gettext(u'Next Step') 
    XXXXXXXXX
  XXXXXX

XXXXXXX
BBBBBBBB
