XBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
  BBBBBBBBBB

  XXXX XXXXXXXXXXXXXXXXXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       gettext(u'Tell us about the property') 
    XXXXXX

    XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
       gettext(u'Engineering details help us prepare the right equipment for your system.') 
    XXXX

    XXXX XXXXXXXXXXXXXXXXXX

      XXXXXX XXXXXXXXXXXXXXXXXXX
         gettext(u'Property Type') 
        XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXX gettext(u'Select type') XXXXXXXXX

          XXXXXXX XXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXXXBBBBBX
             gettext(u'Apartment') 
          XXXXXXXXX

          XXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBB BB BBBBBBBXXXXXXXXBBBBBX
             gettext(u'Villa') 
          XXXXXXXXX

          XXXXXXX XXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBXXXXXXXXBBBBBX
             gettext(u'Commercial') 
          XXXXXXXXX
        XXXXXXXXX
      XXXXXXXX

      XXXXXX XXXXXXXXXXXXXXXXXXX
         gettext(u'Year of Construction') 
        XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXX gettext(u'Select range') XXXXXXXXX

          XXXXXXX XXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBXXXXXXXXBBBBBX
             gettext(u'Before 1980') 
          XXXXXXXXX

          XXXXXXX XXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXXXBBBBBX
             gettext(u'1980 - 2000') 
          XXXXXXXXX

          XXXXXXX XXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBXXXXXXXXBBBBBX
             gettext(u'After 2000') 
          XXXXXXXXX
        XXXXXXXXX
      XXXXXXXX

    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXX
      XXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
           gettext(u'Has the electrical system been upgraded?') 
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Major renewals of fuse box, wiring, or grounding.') 
        XXXXXX
      XXXXXX

      XXXXXX XXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXXXXX
               BB BBBBBBBBBBBBBBBBBBBBXXXXXXXBBBBBX
        XXXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXX
    XXXXXX

  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXX XXXXXXXXXX
       XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BXX
        gettext(u'Back') 
    XXXX

    XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
       gettext(u'Continue') 
    XXXXXXXXX
  XXXXXX

XXXXXXX
BBBBBBBB
