XBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBBBBBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXX gettext(u'Booking Received!') XXXXX

  XXX
    BB BBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBB
       gettext(u'\n      Your Nessafe electrician is scheduled for %(date)s.\n      A confirmation has been sent to your email.\n      ') 
      SSSS SSSSSSS SSSSSSSSSSS SS SSSSSSSSS SSS SSSSSSSSS
      S SSSSSSSSSSSS SSS SSSS SSSS SS SSSS SSSSSS
      
    BBBB
       gettext(u'\n      Your Nessafe electrician is scheduled for %(date)s.\n      A confirmation has been sent to your email.\n      ') 
      SSSS SSSSSSS SSSSSSSSSSS SS SSSSSSSSS SSS SSSSSSSSS
      S SSSSSSSSSSSS SSS SSSS SSSS SS SSSS SSSSSS
      
    BBBBB
  XXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX gettext(u'Confirmation ID') XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX gettext(u'Time Assigned') XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        BB BBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
          
        BBBB
          FFFFFFFFFFFFFF FFF
        BBBBB
      XXXXXX
    XXXXXX

  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BB BBBBBBB
      XX XXXXXXXXXX XXXXXXXXXX
         XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBXX
          gettext(u'Add to Calendar') 
      XXXX
    BBBBB

    XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBXX
       gettext(u'Go To Home') 
    XXXX
  XXXXXX

XXXXXX

BBBBBBBB
