XBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
  BBBBBBBBBB

  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       gettext(u'Apartment & BRF Details') 
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXX
             gettext(u'Is this a BRF (Housing Association) property?') 
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Providing association details helps us coordinate with building management if needed for common electrical lines.') 
          XXXXXX
        XXXXXX

        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
               BB BBBBBBBBBBBBBBBBBXXXXXXXBBBBBX
      XXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXX

      XXXXXX XXXXXXXXXXXXXXXXXXX
         gettext(u'BRF Name / Association') 
        XXXXXX XXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXX
               XXXXXXXXXXXXXXX
               XXXXXXXXXXXXX gettext(u'e.g. BRF Solsidan') X
               XXXXXXXFFFFFFFFFFXX
      XXXXXXXX

      XXXXXX XXXXXXXXXXXXXXXXXXX
         gettext(u'Apartment Number') 
        XXXXXX XXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXX gettext(u'e.g. 1102 (4 digits)') X
               XXXXXXXFFFFFFFFFFXX
      XXXXXXXX

    XXXXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXX XXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BXX
       gettext(u'Back') 
    XXXX
    XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
       gettext(u'Continue') 
    XXXXXXXXX
  XXXXXX

XXXXXXX
BBBBBBBB
