XBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB BBBB
BBBBB BBBBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
  BBBBBBBBBB

  XXXX XXXXXXXXXXXXXXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
         gettext(u'What do you need help with?') 
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                 BB BBBBBBBBBBBBBBBBB BB BBBBBBBBXXXXXXXBBBBB XXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Hourly Electrician') XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Book a licensed electrician by the hour.') 
          XXXXXX
        XXXXXXXX

        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                 BB BBBBBBBBBBBBBBBBB BB BBBBBBB BB BBB BBBBBBBBBBBBBBBBBXXXXXXXBBBBBX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Fixed Service Price') XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Choose a service with a fixed price.') 
          XXXXXX
        XXXXXXXX

      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXX

        BBB BBBBBBB BB BBBBBBBB
          XXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXX
                   XXXXXXXX
                   BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBXXXXXXXBBBBBX

            XXXXX XXXXXXXXXXXXXXXXXXXXX
              BB BBBBBBBBBBBB
                XXXX XXXXXX XXXXXXX
              BBBB
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              BBBBB
            XXXXXXX

            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXX

        BBBBB
          XXXX XXXXXXXXXXXXXXXXXXXX
             gettext(u'No services available.') 
          XXXXXX
        BBBBBB

      XXXXXX

    XXXXXX

    XXXXXX XXXXXXXXXXXXXXXXXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Request Summary') XXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Appointment') XXXXXXX
        XXXXXX
          FFFFFFFFFFFF FFF FFFFF X
          FFFFFFFFFFFFFF FFF
        XXXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Location') XXXXXXX
        XXXXXX
          FFFFFFFFFFFF FFF FFFFFFFX
          FFFFFFFFFFFFFFFFF
        XXXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBB BB BBBBBBBB
          XXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Hourly Rate') XXXXXXX
          XXXXXXFFFFFFFFFFF  X  gettext(u'hour') XXXXXXX
        BBBB
          XXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Fixed Services Total') XXXXXXX
          XXXXXXFFFFFFFFFFF XXXXXXX
        BBBBB
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
             XXXXX gettext(u'Map') XX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX gettext(u'Guaranteed Pro') XXXXXXXXX
        XXXXXX
           gettext(u'All RWM EL pros are licensed, bonded, and insured for your peace of mind.') 
        XXXXXXX
      XXXXXX

    XXXXXXXX

  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXX XXXXXXXXXX
       XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BXX
        gettext(u'Back') 
    XXXX

    XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
       gettext(u'Continue') 
    XXXXXXXXX
  XXXXXX

XXXXXXX

XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
    XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXX XXXXXX X XX XX X
      XXX XXXX X XXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XX XXXXXXXXXXXXXXX XXXX X XXXXXXXXXXXX
      XXX
      XX XXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXX XXXXXXXXXX
      X
    XX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXX
  XXX
XXXXXXXXX

BBBBBBBB
