XBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
  BBBBBBBBBB

  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       gettext(u'Visual Documentation') 
    XXXXXX

    XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
       gettext(u'Please upload photos of the area or existing electrical cabinet.') 
       gettext(u'This allows our experts to bring the correct parts and reduces site time.') 
       gettext(u'Supports JPG, PNG, PDF, and MP4 (Max 20MB).') 
    XXXX

    XXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXX
         gettext(u'Drag and drop files here') 
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXX
         gettext(u'or click to browse from your computer') 
      XXXXXX

      XXXXXX XXXXXXXXXXXXXXXXXXX
         gettext(u'Choose Files') 
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX
      XXXXXXXX
    XXXXXX

    BB BBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXXXX
        BBB BBBB BB BBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
          XXXXXX
        BBBBBB
      XXXXXX
    BBBBB
  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXX XXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BXX
       gettext(u'Back') 
    XXXX
    XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
       gettext(u'Continue') 
    XXXXXXXXX
  XXXXXX

XXXXXXX
BBBBBBBB
