BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBB BBBB

BBBBB BBBBBBBBBBBBBBB

XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX

  BBBBBBBBBB

  XXXX XXXXXXXXXXXXXXXXXXXXXXXX



    XXXX XXXXXXXXXXXXXXXXXXXXXXX

      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

       gettext(u'When would you like us to come?') 

    XXXXXX



    BB BBBBBBBBBBBBBBBBB BB BBBBBBBB

      XXXX XXXXXXXXXXXXXXXXXXXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXX

          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

           gettext(u'Estimated Duration') 

        XXXXXX



        XXXX XXXXXXXXXXXXXXXXXX

          XXXXXX XXXXXXXXXXXXXXXXXXX

             gettext(u'Estimated hours') 

            XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX

              XXXXXXX XXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXBBBBBX gettext(u'1 hour') XXXXXXXXX

              XXXXXXX XXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXBBBBBX gettext(u'2 hours') XXXXXXXXX

              XXXXXXX XXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXBBBBBX gettext(u'3 hours') XXXXXXXXX

              XXXXXXX XXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXBBBBBX gettext(u'4 hours') XXXXXXXXX

              XXXXXXX XXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXBBBBBX gettext(u'5 hours') XXXXXXXXX

              XXXXXXX XXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXBBBBBX gettext(u'6 hours') XXXXXXXXX

              XXXXXXX XXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXBBBBBX gettext(u'7 hours') XXXXXXXXX

              XXXXXXX XXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXBBBBBX gettext(u'8 hours') XXXXXXXXX

            XXXXXXXXX

          XXXXXXXX



          XXXX XXXXXXXXXXXXXXXXXXX

            XXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Estimated price') XXXXXXX

            XXXX XXXXXXXXXXXXXXXXXXXXXX

              XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX

            XXXXXX

          XXXXXX

        XXXXXX

      XXXXXX

    BBBBB



    XXXX XXXXXXXXXXXXXXXXXXXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXXXX

        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

         gettext(u'Primary Choice') 

      XXXXXX



      XXXX XXXXXXXXXXXXXXXXXX

        XXXXXX XXXXXXXXXXXXXXXXXXX

           gettext(u'Select Date') 

          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFFXX

        XXXXXXXX



        XXXXXX XXXXXXXXXXXXXXXXXXX

           gettext(u'Select Time Slot') 

          XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX

            XXXXXXX XXXXXXXXX gettext(u'Select time slot') XXXXXXXXX

            BBB BBBB BB BBBBBBBBBBBBBBB

              XXXXXXX XXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBXXXXXXXXBBBBBX

                

              XXXXXXXXX

            BBBBBB

          XXXXXXXXX

        XXXXXXXX

      XXXXXX

    XXXXXX



    XXXX XXXXXXXXXXXXXXXXXXXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXXXX

        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

         gettext(u'Alternative Choice (Optional)') 

      XXXXXX



      XXXX XXXXXXXXXXXXXXXXXXXXXX

         gettext(u'Adding an alternative window helps us confirm your booking faster.') 

      XXXXXX



      XXXX XXXXXXXXXXXXXXXXXX

        XXXXXX XXXXXXXXXXXXXXXXXXX

           gettext(u'Select Date') 

          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFFXX

        XXXXXXXX



        XXXXXX XXXXXXXXXXXXXXXXXXX

           gettext(u'Select Time Slot') 

          XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX

            XXXXXXX XXXXXXXXX gettext(u'Select time slot') XXXXXXXXX

            BBB BBBB BB BBBBBBBBBBBBBBBBBBB

              XXXXXXX XXXXXXXX BB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBBXXXXXXXXBBBBBX

                

              XXXXXXXXX

            BBBBBB

          XXXXXXXXX

        XXXXXXXX

      XXXXXX

    XXXXXX

  XXXXXX



  XXXX XXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXXXXX XXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BXX

       gettext(u'Back') 

    XXXX

    XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX

       gettext(u'Continue') 

    XXXXXXXXX

  XXXXXX

XXXXXXX
BBBBBBBB
