XBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
  BBBBBBBBBB

  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       gettext(u'Who is the booking for?') 
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXX

      XXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
               BB BBBBBBBBBBBBBBBBB BB BBBBBBBBBXXXXXXXBBBBB XXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Private Customer') XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Individual home services, repairs, and electrical installations for your residence.') 
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
             gettext(u'Eligible for ROT tax deduction') 
          XXXXXX
        XXXXXX
      XXXXXXXX

      XXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
               BB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBXXXXXXXBBBBBX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Business / BRF') XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Commercial properties, offices, housing associations (BRF), and organizations.') 
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
             gettext(u'VAT invoice included') 
          XXXXXX
        XXXXXX
      XXXXXXXX

    XXXXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       gettext(u'Your contact details') 
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXX

      XXXXXX XXXXXXXXXXXXXXXXXXX
         gettext(u'Full Name') 
        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
               XXXXXXXXXXXXXXXX
               XXXXXXXFFFFFFFFFFX
               XXXXXXXXXXXXX gettext(u'e.g. Erik Andersson') X
               XXXXXXXXX
      XXXXXXXX

      XXXXXX XXXXXXXXXXXXXXXXXXX
         gettext(u'Phone Number') 
        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
               XXXXXXXXXXXX
               XXXXXXXFFFFFFFFFFX
               XXXXXXXXXXXXXXXX XX XXX XX XXXX
      XXXXXXXX

      XXXXXX XXXXXXXXXXXXXXXXX XXXXXX
         gettext(u'Email Address') 
        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
               XXXXXXXXXXXX
               XXXXXXXFFFFFFFFFFX
               XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
               XXXXXXXXX
      XXXXXXXX

    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
       gettext(u"We'll send your booking confirmation and estimate to this address.") 
    XXXXXX

  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXX XXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBXX
       gettext(u'Back') 
    XXXX
    XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
       gettext(u'Continue') 
    XXXXXXXXX
  XXXXXX

XXXXXXX
BBBBBBBB
