XBBBB BBBBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXXXXXXXX XXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXX XXX X X X X X XXXXXXX X X X X X XXXXXXXX X X X XXXX XXXXXXXX X X X X XXXXXXXXX X X X X XXXXXX XXX X X X XXX XXXXXXXXX X X X XXXXXXXXX XXXXX X X X X X XXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXX
      XXXXXX

      XXXXXXXX XX XX XXXX XXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXX XXXXXX XXXX XXXXXXXXXXXXX

      BB BBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX XXXXXXXXXXXXXXX
      BBBBB

      XXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXX XXX X X X X X XXXXXXXXXX X X X XXX XXXXXXXXX X X X X XXXXXXX XXXXXX X X X X X XXXXX X X X XXX XXXXX X X X XXXXXXXXXX X X X X XXXXXX XXX X X X XXX XXXXXXXXXXXXXXX X X X XXXXXXXXXXX
            XXXXXX
          XXXXXXX
          XXXXXXXXXX XXXXXXXXX
        XXXXXXXXX
      XXXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBXXXXXXXX XX XXXXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
  XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX
XXXXXXX
