XBBBB BBBBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXXXXXXXX XXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXXX
      XXXXXX

      XXXXXXXXXX XXXX XXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX

      BB BBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXX XXXXXX XXXXXXXXXXXX
      BBBBB

      XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        BBBBBBBBBB
        
        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXX
            XXXXXXXXX XXX XXXXXXX XXXX XXXXXXX XXXX XXXXXXX XXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            BBB BBBBBB BB BBBBBBBBBBBBBBBBB
              XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            BBBBBB
          XXXXXX
        XXXXXXXXXX

        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX XXXXXXXXXXXX
            XXXXX XXX XXXX XXXXXXXXXXX XX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXX XXXXXXXXXXXX
              
              BB BBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXX
              
              BB BBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXX
              
              BB BBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXX
              
              BB BBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
            XXXXXX
          XXXXXX
        XXXXXXXXXX

        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXX
            XXXXXXX XXX XXXXXXX XXXXXX XXX XXXXX XXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXX XXXXXXXXXXXXXXX
              
              BB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXX
              
              BB BBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXX XXXXXXXXXXXX
              
              BB BBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXX
              
              BB BBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
            XXXXXX
          XXXXXX
        XXXXXXXXXX

        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX X XXXXXXXXXXXXXX
            XXXXXXX XX XXXXXXXXX XXX XXXXX XXXXXXXX XXX XXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXX XXXXXXXXXXXX
              
              BB BBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
              BB BBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
            XXXXXX
          XXXXXX
        XXXXXXXXXX

        XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXX XXXXXXXXXX
              
              BB BBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
            XXXXXX
          XXXXXX
        XXXXXXXXXX

        XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX XXXXXXXXXXXX
            XXXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXX XXXXXXXXXXXX
              
              BB BBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
              
              BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
              XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
              
              BB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
            XXXXXX
          XXXXXX
        XXXXXXXXXX

        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXXXXXXX X XXXXXX XXXXXXXX XX XXXXXXX XXXX XXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXX
              
              BB BBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
              
              BB BBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
            XXXXXX
          XXXXXX
        XXXXXXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXX XX XXXXXXX XXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXX

        BB BBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXX XXXXXX XXXXXXXXXXXX
        BBBBB

        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXX XX XXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXXXXXX XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
  XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
    XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXX X XX XX X
      XXX XXXX X XXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XX XXXXXXXXXXXXXXX XXXX X XXXXXXXXXXXX
      XXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXX XXXXXXXXXXX
      XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXX XXXXXXXXXXXX
    XX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXX
  XXX
XXXXXXXXX
XXXXXXX
XXXXXXX
