XBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBBBBBXXXX XXXXXX XXXXXX XX XXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXX
            XXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX XXX XXXX XXX XXXX XX XXXXXX XXXX XXXXXXXXXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXX
        XXXXXX
    XXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        BBBBBBBBBB
        XX XXXXXXXXXXXXXXX XXXXXX XXXXXXBBB BBBBBBBBXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX
XXXXXXXXXX
BBBBBBBB
