XBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBBB BBBB

BBBBB BBBBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBBBBBXXXX XXX XXXXXXX XXX XXXXXBBBBBBBB

BBBBB BBBBBBB
BB BBBBBBBBBBBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXX
            XXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXX XX XXXX XXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
        BBB BBBBB BB BBBB
            XXXX XXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXFFFFFFFFFFFXXXXXXX
            XXXXXX
        BBBBBB
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXX XXXXXX XXXXXXBBB BBBBBBBBXXXXXXXXXX
    XXXXXX
XXXXXXXXXX
BBBB
XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXX
            XXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XX XXXX XXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        BBBBBBBBBB
        
        BBB BBBBB BB BBBB
            XXXX XXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXX
                
                BB BBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                BBBBB
            XXXXXX
        BBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXX XXXXXX XXXXXXBBB BBBBBBBBXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXXX
XXXXXXXXXX
BBBBB
BBBBBBBB
