XBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBBB BBBB

BBBBB BBBBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBBBBBXXXXXX XXX XXXXXXX XXXXXXXX XX XXXX XXXXXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXX
            XXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXFFFFFF XXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXBBB BBBBBBBBBBXXXXX XXXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            BBB BBBBB BB BBBBBB
                XXXXXXFFFFFXXXXXXX
            BBBBBB
            XXXXXXXXXXXXXXXXXXXX
        XXXXXX
        BBB BBB BB BBBBB
            XXXX XXXXXXXXXXXXXXXXXX
                BBB BBBBB BB BBBBBB
                    XXXXXXFFFFFFFFFFFFFFFFFFFFFFXXXXXXX
                BBBBBB
                XXXXX XXXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBB
                      XX XXXXXXBBB BBBBBBBBBB BBBBBBXXXXXXXXXXXX
                    BBBBB
                    XX XXXXXXBBB BBBBBBBB BBBBBBXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBB BBBBBBXXXXXXXXXXXX
                XXXXXXX
            XXXXXX
        BBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX
        BBBBBB
    XXXXXX
XXXXXXXXXX
BBBBBBBB
