XBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBB BBBB

BBBBB BBBBBBBBBBXXXXXXX XXXXXXXXBBBBBBBB
BBBBB BBBBBBBBBBBBBXXXXXXXXXXXX XXXX XXXXXXXXXXX XXX XXXXXXX XXXXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXX
            XXXXXXXXXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXFFFFFF XXXXXXXXXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            BBB BBBBB BB BBBBBB
                XXXXXXFFFFFXXXXXXX
            BBBBBB
        XXXXXX
        BBB BBB BB BBBBB
            XXXX XXXXXXXXXXXXXXXXXX
                BBB BBBBB BB BBBBBB
                    XXXXXXFFFFFFFFFFFFFFFFFFFFFFXXXXXXX
                BBBBBB
            XXXXXX
        BBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX
        BBBBBB
    XXXXXX
XXXXXXXXXX
BBBBBBBB
