XBBBB BBBBBB BBBBBBBBBBBBBBBBBB BBBB
XXXXXXXXX XXXXX
BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBB
XXXXX XXXXXXX XXXXXBB BBBBBBBBBBBBBBBB BB BBBBXXXBBBBXXXBBBBBXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXBBBBB BBBBB gettext(u'Consultation Booking') BBBBBBBBXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBB BB BBBB
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    BBBBB
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
    BBBBB BBBBBBBBBBBBBBBBB
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Step %(step)s of %(total)s') SSSS SSSSSSSS SS SSSSSSSSS
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'%(percent)s%%%% Complete') SSSSSSSSSSSSSSS SSSSSSSS
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBB BBBBBBBBBBBBBBBB
            XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                BBBBBBBBBB
                BBBBB BBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB BBBBBBBBBBBBBBB
                XXXXXX
            XXXXXXX
        XXXXXX
    XXXXXX
XXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXX XXXX
      XXXXXX
      XXXX gettext(u'Electrical &amp; Infrastructure Solutions') XXXXX
      XX XXXXXXXXXXXXXXXXXXXX
         gettext(u'Licensed electrical work, upgrades, and system installations — built right and built to last.') 
         gettext(u'Delivering the gold standard in smart home technology and enterprise power systems.') 
      XXXX
      XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXX gettext(u'Company') XXXXX
      XXXX
        XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXX gettext(u'About us') XXXXXXXXX
        XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXX gettext(u'Terms &amp; Conditions') XXXXXXXXX
        XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBXX gettext(u'Privacy Policy') XXXXXXXXX
        XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBXX gettext(u'Cookies') XXXXXXXXX
        XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBXX gettext(u'Customer Support') XXXXXXXXX
        XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBXX gettext(u'Contact us') XXXXXXXXX
      XXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXX gettext(u'Contact') XXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXX gettext(u'Address') XXXXXXX  gettext(u'Rådmansgatan 12, 114 44 Stockholm, Sweden') XXXXX
        XXXXXXXXXX gettext(u'Phone') XXXXXXX XXX X XXX XXX XXXXXXX
        XXXXXXXXXX gettext(u'Email') XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXXX
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'© 2026 RWM EL. All rights reserved.') XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBXX gettext(u'Privacy') XXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBXX gettext(u'Cookies') XXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBXX gettext(u'FAQ') XXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXX gettext(u'Terms') XXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Sweden (EN)') XXXXXX
  XXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
BBBBB BBBBBBBBBBBBBBBB
XXXXXXX
XXXXXXX
