XBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBB
XX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u"We'll use these details to confirm your consultation slot.") XXXX
BBBBBBBB

BBBBB BBBBBBB
BB BBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Your first consultation is free.') XXXXXX
BBBBB
XXXX XXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Are you a private individual or a business?') XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
        BBB BBBBBB BB BBBBBBBBBBBBBBBBB
            XXXXXX XXXXXXXXXXXXXXXXXXXXXX
                
                XXXXXXXXXXXXX
            XXXXXXXX
        BBBBBB
    XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Personal ID number') XXXXXXXX
    
XXXXXX

XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Company name') XXXXXXXX
    
XXXXXX
XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Organization number') XXXXXXXX
    
XXXXXX
XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Company address') XXXXXXXX
    
XXXXXX

XXXX XXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Full Name') XXXXXXXX
    
XXXXXX

XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Email') XXXXXXXX
        
    XXXXXX
    XXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Phone Number') XXXXXXXX
        
    XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'When are you available for a call?') XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        BBB BBBBBB BB BBBBBBBBBBBBBBBBBBBBBB
            XXXXXX XXXXXXXXXXXXXXXXX
                
                XXXXXXXXXXXXX
            XXXXXXXX
        BBBBBB
    XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Preferred time window') XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        BBB BBBBBB BB BBBBBBBBBBBBBBBB
            XXXXXX XXXXXXXXXXXXXXXXXX
                
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX
        BBBBBB
    XXXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBBB
XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Back') XXXX
XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Next Step') XXXXXXXXX
BBBBBBBB
