XBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBB
XX XXXXXXXXXXXXXXXXXXXXXXXXX
     gettext(u'Select all that apply so we can match you with the right specialist.') 
XXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXX
    BBB BBBBBB BB BBBBBBBBBBBBB
        XXXXXX XXXXXXXXXXXXXXXXXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBB BB B
                    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXX XXX XXXXXXX X XXXXXXXXXXXXXXX
                    XXXXXX
                BBBB BBBBBBBBBBBBBBB BB B
                    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX X X XXX X XXX XXX XXX XXX X XXXXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX
                BBBB BBBBBBBBBBBBBBB BB B
                    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXXX
                BBBB BBBBBBBBBBBBBBB BB B
                    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXX XXXX X X X X X XXX XXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXX X X XXX X XXX XXX X X X X XXXX XXXXXXXX XXXXXXX XXXXXXX XXX X XXXXXXXXXXXXXX
                    XXXXXX
                BBBB BBBBBBBBBBBBBBB BB B
                    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXX XXXX XXXXXXX XXXXX XXXXXXX XXX X XXXX XXXXXXXXXXXXXXX
                    XXXXXX
                BBBB
                    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXX XXX X X X X X X X X X X X XXXXXX XXXXXXXXXX XXX X X XXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXX X X XXXXX XXXXXXXXXXXXXXXX XXX X X XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXX X X XXXXXXXXXXXXXXXXXXXX XXX X X X XXXXXXXXX XXXXXXXXXXX XXX XXXXXXX XXX X X X XXXXXXXXXXXXXXXXX XXX X X X XXX XXXXXXXXX XXX XXXXXXX XXXXXXX XXX X X X X XXXXXXXXXXXX
                    XXXXXX
                BBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBB BB B
                    XXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Panel upgrades, rewiring, outlets') XXXXXX
                BBBB BBBBBBBBBBBBBBB BB B
                    XXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Indoor/outdoor, recessed, landscape') XXXXXX
                BBBB BBBBBBBBBBBBBBB BB B
                    XXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Home station installation') XXXXXX
                BBBB BBBBBBBBBBBBBBB BB B
                    XXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Smart locks, cameras, thermostat') XXXXXX
                BBBB BBBBBBBBBBBBBBB BB B
                    XXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Repairing sparks, shorts, or failures') XXXXXX
                BBBB
                    XXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Routine inspections and testing') XXXXXX
                BBBBB
            XXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX
    BBBBBB
XXXXXX

XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Is this urgent?') XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Select \\') 
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
        BBB BBBBBB BB BBBBBBBBBBB
            XXXXXX XXXXXXXXXXXXXXXXXXXXXX
                
                XXXXXXXXXXXXX
            XXXXXXXX
        BBBBBB
    XXXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBBB
XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
     gettext(u'Back') 
XXXX
XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
     gettext(u'Continue') 
XXXXXXXXX
BBBBBBBB
