XBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBB
XX XXXXXXXXXXXXXXXXXXXXXXXXX
     gettext(u'Provide the basic details so we can tailor your consultation.') 
XXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXX
    BBB BBBBBB BB BBBBBBBBBBBBBBBBBB
        XXXXXX XXXXXXXXXXXXXXXXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBB BB B
                        XXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XXXXXX
                    BBBB BBBBBBBBBBBBBBB BB B
                        XXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                    BBBB BBBBBBBBBBBBBBB BB B
                        XXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XXXXXX
                    BBBB
                        XXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                        XXXXXX
                    BBBBB
                XXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX
    BBBBBB
XXXXXX

XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Other property type') XXXXXXXX
    
XXXXXX

XXXX XXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'What is the approximate size?') XXXXXXXX
    
XXXXXX

XXXX XXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Year built or last renovated?') XXXXXXXX
    
    XXXX XXXXXXXXXXXXXXXXXX
         gettext(u"If you're not sure, provide an approximate year.") 
    XXXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBBB
XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
     gettext(u'Back') 
XXXX
XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
     gettext(u'Continue') 
XXXXXXXXX
BBBBBBBB
