XBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBB
XX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Photos or videos help us assess faster. Your data is encrypted and secure.') XXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXX
                XXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXX X X X X XXX X X X X X X XXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Browse Files') XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX gettext(u'JPG, PNG up to 10MB') XXXXXX
        
    XXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXX
                XXXXX XXXXX XXXXXX X X X X X XXXXXXXXXXXXXXXXXXXXX X X X XXX XXXXXXXX XXXXXXXXXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Select Video') XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX gettext(u'MP4, MOV up to 50MB') XXXXXX
        
    XXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXX
                XXXXX XXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Select Docs') XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX gettext(u'PDF, DOCX up to 20MB') XXXXXX
        
    XXXXXXXX
XXXXXX
XXXX XXXXXXXXXXXXXXXXXXXX gettext(u'No files selected yet. You can skip this step and add them later.') XXXXXX
BBBBBBBB

BBBBB BBBBBBB
XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Back') XXXX
XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Next Step') XXXXXXXXX
BBBBBBBB
