XBBBB BBBBBB BBBB
XXXXXXXXX XXXXX
BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBB
XXXXX XXXXXXX XXXXXBB BBBBBBBBBBBBBBBB BB BBBBXXXBBBBXXXBBBBBXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXX gettext(u'Request Received') XXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBB BB BBBB
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    BBBBB
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
XXXXXXX
XXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX gettext(u"Thanks - we've received your request") XXXXX
            XXX gettext(u'Our team will review your information and contact you shortly to confirm the consultation and next steps.') XXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBXX gettext(u'Back to Home') XXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BXX gettext(u'Book an Electrician') XXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Urgent requirement? If your issue becomes urgent, you can book a licensed electrician directly.') 
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXX
XXXXXXX
XXXXXXX
