from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = "electricity"

urlpatterns = [
    path("", views.home, name="home"),
    path("services/", views.services, name="services"),
    path("terms/", views.terms, name="terms"),
    path("privacy/", views.privacy, name="privacy"),
    path("cookies/", views.cookies, name="cookies"),
    path("about/", views.about, name="about"),
    path("on-call/", views.on_call, name="on_call"),
    path("support/", views.support, name="support"),
    path("contact/", views.contact, name="contact"),
    path("faq/", views.faq, name="faq"),
    path("zip-check/<str:flow>/", views.zip_check, name="zip_check"),
    path("outside-area/<str:flow>/<str:zip_code>/", views.outside_area, name="outside_area"),
    path("accounts/login/", auth_views.LoginView.as_view(template_name="registration/login.html"), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("accounts/signup/", views.signup, name="signup"),
    path("accounts/profile/", views.login_redirect, name="login_redirect"),
    path("dashboard/", views.external_dashboard, name="dashboard"),
    path("dashboard/notifications/feed/", views.admin_notifications_feed, name="admin_notifications_feed"),
    path("dashboard/notifications/read/", views.admin_notifications_mark_read, name="admin_notifications_mark_read"),
    path("dashboard/services/", views.dashboard_services, name="dashboard_services"),
    path("dashboard/services/add/", views.dashboard_services_add, name="dashboard_services_add"),
    path("dashboard/services/<int:pk>/edit/", views.dashboard_services_edit, name="dashboard_services_edit"),
    path("dashboard/services/<int:pk>/delete/", views.dashboard_services_delete, name="dashboard_services_delete"),
    path("dashboard/pricing/", views.dashboard_pricing, name="dashboard_pricing"),
    path("dashboard/pricing/add/", views.dashboard_pricing_add, name="dashboard_pricing_add"),
    path("dashboard/pricing/<int:pk>/edit/", views.dashboard_pricing_edit, name="dashboard_pricing_edit"),
    path("dashboard/pricing/<int:pk>/delete/", views.dashboard_pricing_delete, name="dashboard_pricing_delete"),
    path("dashboard/requests/", views.dashboard_requests, name="dashboard_requests"),
    path("dashboard/requests/add/", views.dashboard_requests_add, name="dashboard_requests_add"),
    path("dashboard/requests/<int:pk>/edit/", views.dashboard_requests_edit, name="dashboard_requests_edit"),
    path("dashboard/requests/<int:pk>/delete/", views.dashboard_requests_delete, name="dashboard_requests_delete"),
    path("dashboard/bookings/", views.dashboard_bookings, name="dashboard_bookings"),
    path("dashboard/bookings/add/", views.dashboard_bookings_add, name="dashboard_bookings_add"),
    path("dashboard/bookings/<int:pk>/edit/", views.dashboard_bookings_edit, name="dashboard_bookings_edit"),
    path("dashboard/bookings/<int:pk>/delete/", views.dashboard_bookings_delete, name="dashboard_bookings_delete"),
    path("dashboard/bookings/<int:pk>/assign/", views.dashboard_bookings_assign, name="dashboard_bookings_assign"),
    path("dashboard/service-bookings/", views.dashboard_service_bookings, name="dashboard_service_bookings"),
    path("dashboard/service-bookings/add/", views.dashboard_service_bookings_add, name="dashboard_service_bookings_add"),
    path(
        "dashboard/service-bookings/<int:pk>/edit/",
        views.dashboard_service_bookings_edit,
        name="dashboard_service_bookings_edit",
    ),
    path(
        "dashboard/service-bookings/<int:pk>/assign/",
        views.dashboard_service_bookings_assign,
        name="dashboard_service_bookings_assign",
    ),
    path(
        "dashboard/service-bookings/<int:pk>/delete/",
        views.dashboard_service_bookings_delete,
        name="dashboard_service_bookings_delete",
    ),
    path("dashboard/electrician-bookings/", views.dashboard_electrician_bookings, name="dashboard_electrician_bookings"),
    path(
        "dashboard/electrician-bookings/<int:pk>/assign/",
        views.dashboard_electrician_bookings_assign,
        name="dashboard_electrician_bookings_assign",
    ),
    path(
        "dashboard/electrician-bookings/add/",
        views.dashboard_electrician_bookings_add,
        name="dashboard_electrician_bookings_add",
    ),
    path(
        "dashboard/electrician-bookings/<int:pk>/edit/",
        views.dashboard_electrician_bookings_edit,
        name="dashboard_electrician_bookings_edit",
    ),
    path(
        "dashboard/electrician-bookings/<int:pk>/delete/",
        views.dashboard_electrician_bookings_delete,
        name="dashboard_electrician_bookings_delete",
    ),
    path("dashboard/on-call-bookings/", views.dashboard_on_call_bookings, name="dashboard_on_call_bookings"),
    path("dashboard/on-call-bookings/add/", views.dashboard_on_call_bookings_add, name="dashboard_on_call_bookings_add"),
    path(
        "dashboard/on-call-bookings/<int:pk>/edit/",
        views.dashboard_on_call_bookings_edit,
        name="dashboard_on_call_bookings_edit",
    ),
    path(
        "dashboard/on-call-bookings/<int:pk>/assign/",
        views.dashboard_on_call_bookings_assign,
        name="dashboard_on_call_bookings_assign",
    ),
    path(
        "dashboard/on-call-bookings/<int:pk>/delete/",
        views.dashboard_on_call_bookings_delete,
        name="dashboard_on_call_bookings_delete",
    ),
    path("dashboard/profiles/", views.dashboard_profiles, name="dashboard_profiles"),
    path("dashboard/profiles/add/", views.dashboard_profiles_add, name="dashboard_profiles_add"),
    path("dashboard/profiles/<int:pk>/edit/", views.dashboard_profiles_edit, name="dashboard_profiles_edit"),
    path("dashboard/profiles/<int:pk>/delete/", views.dashboard_profiles_delete, name="dashboard_profiles_delete"),
    path("dashboard/providers/", views.dashboard_providers, name="dashboard_providers"),
    path("dashboard/provider-shifts/", views.dashboard_provider_shifts, name="dashboard_provider_shifts"),
    path("dashboard/provider-shifts/add/", views.dashboard_provider_shifts_add, name="dashboard_provider_shifts_add"),
    path(
        "dashboard/provider-shifts/<int:pk>/edit/",
        views.dashboard_provider_shifts_edit,
        name="dashboard_provider_shifts_edit",
    ),
    path(
        "dashboard/provider-shifts/<int:pk>/delete/",
        views.dashboard_provider_shifts_delete,
        name="dashboard_provider_shifts_delete",
    ),
    path("dashboard/providers/add/", views.dashboard_providers_add, name="dashboard_providers_add"),
    path("dashboard/providers/<int:pk>/edit/", views.dashboard_providers_edit, name="dashboard_providers_edit"),
    path("dashboard/providers/<int:pk>/delete/", views.dashboard_providers_delete, name="dashboard_providers_delete"),
    path("dashboard/users/", views.dashboard_users, name="dashboard_users"),
    path("dashboard/users/add/", views.dashboard_users_add, name="dashboard_users_add"),
    path("dashboard/users/<int:pk>/edit/", views.dashboard_users_edit, name="dashboard_users_edit"),
    path("dashboard/users/<int:pk>/delete/", views.dashboard_users_delete, name="dashboard_users_delete"),
    path("dashboard/support-tickets/", views.dashboard_support_tickets, name="dashboard_support_tickets"),
    path("dashboard/support-tickets/add/", views.dashboard_support_tickets_add, name="dashboard_support_tickets_add"),
    path(
        "dashboard/support-tickets/<int:pk>/edit/",
        views.dashboard_support_tickets_edit,
        name="dashboard_support_tickets_edit",
    ),
    path(
        "dashboard/support-tickets/<int:pk>/delete/",
        views.dashboard_support_tickets_delete,
        name="dashboard_support_tickets_delete",
    ),
    path("dashboard/faq/", views.dashboard_faq, name="dashboard_faq"),
    path("dashboard/faq/add/", views.dashboard_faq_add, name="dashboard_faq_add"),
    path("dashboard/faq/<int:pk>/edit/", views.dashboard_faq_edit, name="dashboard_faq_edit"),
    path("dashboard/faq/<int:pk>/delete/", views.dashboard_faq_delete, name="dashboard_faq_delete"),
    path("dashboard/zip-codes/", views.dashboard_zip_codes, name="dashboard_zip_codes"),
    path("dashboard/zip-codes/add/", views.dashboard_zip_codes_add, name="dashboard_zip_codes_add"),
    path(
        "dashboard/zip-codes/<int:pk>/edit/",
        views.dashboard_zip_codes_edit,
        name="dashboard_zip_codes_edit",
    ),
    path(
        "dashboard/zip-codes/<int:pk>/delete/",
        views.dashboard_zip_codes_delete,
        name="dashboard_zip_codes_delete",
    ),
    path(
        "dashboard/outside-area/",
        views.dashboard_outside_area_requests,
        name="dashboard_outside_area_requests",
    ),
    path(
        "dashboard/outside-area/add/",
        views.dashboard_outside_area_requests_add,
        name="dashboard_outside_area_requests_add",
    ),
    path(
        "dashboard/outside-area/<int:pk>/edit/",
        views.dashboard_outside_area_requests_edit,
        name="dashboard_outside_area_requests_edit",
    ),
    path(
        "dashboard/outside-area/<int:pk>/delete/",
        views.dashboard_outside_area_requests_delete,
        name="dashboard_outside_area_requests_delete",
    ),
    path("provider/dashboard/", views.provider_dashboard, name="provider_dashboard"),
    path("provider/orders/<int:pk>/", views.provider_order_detail, name="provider_order_detail"),
    path(
        "provider/service-bookings/<int:pk>/",
        views.provider_service_booking_detail,
        name="provider_service_booking_detail",
    ),
    path(
        "provider/service-bookings/<int:pk>/extend/",
        views.provider_service_booking_extend,
        name="provider_service_booking_extend",
    ),
    path(
        "provider/service-bookings/<int:pk>/status/",
        views.provider_service_booking_update_status,
        name="provider_service_booking_update_status",
    ),
    path(
        "provider/on-call-bookings/<int:pk>/",
        views.provider_on_call_booking_detail,
        name="provider_on_call_booking_detail",
    ),
    path("provider/orders/<int:pk>/status/", views.provider_update_status, name="provider_update_status"),
    path("consultation-booking/step-1/", views.booking_step_1, name="booking_step_1"),
    path("consultation-booking/step-2/", views.booking_step_2, name="booking_step_2"),
    path("consultation-booking/step-3/", views.booking_step_3, name="booking_step_3"),
    path("consultation-booking/step-4/", views.booking_step_4, name="booking_step_4"),
    path("consultation-booking/step-5/", views.booking_step_5, name="booking_step_5"),
    path("consultation-booking/step-6/", views.booking_step_6, name="booking_step_6"),
    path("consultation-booking/step-7/", views.booking_step_7, name="booking_step_7"),
    path("consultation-booking/thank-you/", views.booking_thank_you, name="booking_thank_you"),
    path("booking/step-<int:step>/", views.legacy_consultation_booking_step, name="legacy_booking_step"),
    path("booking/thank-you/", views.legacy_consultation_booking_thank_you, name="legacy_booking_thank_you"),
    path("book-electrician/step-<int:step>/", views.electrician_booking_step, name="electrician_booking_step"),
    path("book-electrician/thank-you/", views.electrician_booking_thank_you, name="electrician_booking_thank_you"),
    path("service-booking/step-<int:step>/", views.service_booking_step, name="service_booking_step"),
    path("service-booking/slots/", views.service_booking_slots, name="service_booking_slots"),
    path("service-booking/<int:pk>/calendar/", views.service_booking_calendar, name="service_booking_calendar"),
    path("on-call-booking/step-<int:step>/", views.on_call_booking_step, name="on_call_booking_step"),
]
