from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from django.urls import reverse_lazy
from .forms import UsernameOrEmailPasswordResetForm

app_name = "electricity"

urlpatterns = [
    path("", views.home, name="home"),
    path("services/", views.services, name="services"),
    path("services/page/<slug:slug>/", views.service_detail, name="service_detail"),
    path("services/<slug:slug>/", views.service_category_detail, name="service_category_detail"),
    path("terms/", views.terms, name="terms"),
    path("privacy/", views.privacy, name="privacy"),
    path("cookies/", views.cookies, name="cookies"),
    path("about/", views.about, name="about"),
    path("on-call/", views.on_call, name="on_call"),
    path("support/", views.support, name="support"),
    path("contact/", views.contact, name="contact"),
    path("feedback/", views.feedback, name="feedback"),
    path("faq/", views.faq, name="faq"),
    path("zip-check/<str:flow>/", views.zip_check, name="zip_check"),
    path("outside-area/<str:flow>/<str:zip_code>/", views.outside_area, name="outside_area"),
    path("accounts/login/", auth_views.LoginView.as_view(template_name="registration/login.html"), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "accounts/password-reset/",
        auth_views.PasswordResetView.as_view(
            form_class=UsernameOrEmailPasswordResetForm,
            template_name="electricity/auth/password_reset_form.html",
            email_template_name="electricity/auth/password_reset_email.html",
            subject_template_name="electricity/auth/password_reset_subject.txt",
            success_url=reverse_lazy("electricity:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "accounts/password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(template_name="electricity/auth/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "accounts/reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="electricity/auth/password_reset_confirm.html",
            success_url=reverse_lazy("electricity:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "accounts/reset/done/",
        auth_views.PasswordResetCompleteView.as_view(template_name="electricity/auth/password_reset_complete.html"),
        name="password_reset_complete",
    ),
    path("accounts/signup/", views.signup, name="signup"),
    path("accounts/profile/", views.login_redirect, name="login_redirect"),
    path("dashboard/", views.external_dashboard, name="dashboard"),
    path("dashboard/notifications/feed/", views.admin_notifications_feed, name="admin_notifications_feed"),
    path("dashboard/notifications/read/", views.admin_notifications_mark_read, name="admin_notifications_mark_read"),
    path("dashboard/services/", views.dashboard_services, name="dashboard_services"),
    path("dashboard/services/add/", views.dashboard_services_add, name="dashboard_services_add"),
    path("dashboard/services/<int:pk>/edit/", views.dashboard_services_edit, name="dashboard_services_edit"),
    path("dashboard/services/<int:pk>/delete/", views.dashboard_services_delete, name="dashboard_services_delete"),
    path("dashboard/pricing/", views.dashboard_pricing, name="dashboard_pricing"),
    path("dashboard/pricing/add/", views.dashboard_pricing_add, name="dashboard_pricing_add"),
    path("dashboard/pricing/<int:pk>/edit/", views.dashboard_pricing_edit, name="dashboard_pricing_edit"),
    path("dashboard/pricing/<int:pk>/delete/", views.dashboard_pricing_delete, name="dashboard_pricing_delete"),
    path("dashboard/requests/", views.dashboard_requests, name="dashboard_requests"),
    path("dashboard/requests/add/", views.dashboard_requests_add, name="dashboard_requests_add"),
    path("dashboard/requests/<int:pk>/edit/", views.dashboard_requests_edit, name="dashboard_requests_edit"),
    path("dashboard/requests/<int:pk>/delete/", views.dashboard_requests_delete, name="dashboard_requests_delete"),
    path("dashboard/bookings/", views.dashboard_bookings, name="dashboard_bookings"),
    path("dashboard/bookings/add/", views.dashboard_bookings_add, name="dashboard_bookings_add"),
    path("dashboard/bookings/<int:pk>/edit/", views.dashboard_bookings_edit, name="dashboard_bookings_edit"),
    path("dashboard/bookings/<int:pk>/delete/", views.dashboard_bookings_delete, name="dashboard_bookings_delete"),
    path("dashboard/bookings/<int:pk>/assign/", views.dashboard_bookings_assign, name="dashboard_bookings_assign"),
    path("dashboard/service-bookings/", views.dashboard_service_bookings, name="dashboard_service_bookings"),
    path("dashboard/service-bookings/add/", views.dashboard_service_bookings_add, name="dashboard_service_bookings_add"),
    path(
        "dashboard/service-bookings/<int:pk>/edit/",
        views.dashboard_service_bookings_edit,
        name="dashboard_service_bookings_edit",
    ),
    path(
        "dashboard/service-bookings/<int:pk>/assign/",
        views.dashboard_service_bookings_assign,
        name="dashboard_service_bookings_assign",
    ),
    path(
        "dashboard/service-bookings/<int:pk>/delete/",
        views.dashboard_service_bookings_delete,
        name="dashboard_service_bookings_delete",
    ),
    path("dashboard/electrician-bookings/", views.dashboard_electrician_bookings, name="dashboard_electrician_bookings"),
    path(
        "dashboard/electrician-bookings/<int:pk>/assign/",
        views.dashboard_electrician_bookings_assign,
        name="dashboard_electrician_bookings_assign",
    ),
    path(
        "dashboard/electrician-bookings/add/",
        views.dashboard_electrician_bookings_add,
        name="dashboard_electrician_bookings_add",
    ),
    path(
        "dashboard/electrician-bookings/<int:pk>/edit/",
        views.dashboard_electrician_bookings_edit,
        name="dashboard_electrician_bookings_edit",
    ),
    path(
        "dashboard/electrician-bookings/<int:pk>/delete/",
        views.dashboard_electrician_bookings_delete,
        name="dashboard_electrician_bookings_delete",
    ),
    path("dashboard/on-call-bookings/", views.dashboard_on_call_bookings, name="dashboard_on_call_bookings"),
    path("dashboard/on-call-bookings/add/", views.dashboard_on_call_bookings_add, name="dashboard_on_call_bookings_add"),
    path(
        "dashboard/on-call-bookings/<int:pk>/edit/",
        views.dashboard_on_call_bookings_edit,
        name="dashboard_on_call_bookings_edit",
    ),
    path(
        "dashboard/on-call-bookings/<int:pk>/assign/",
        views.dashboard_on_call_bookings_assign,
        name="dashboard_on_call_bookings_assign",
    ),
    path(
        "dashboard/on-call-bookings/<int:pk>/delete/",
        views.dashboard_on_call_bookings_delete,
        name="dashboard_on_call_bookings_delete",
    ),
    path("dashboard/profiles/", views.dashboard_profiles, name="dashboard_profiles"),
    path("dashboard/profiles/add/", views.dashboard_profiles_add, name="dashboard_profiles_add"),
    path("dashboard/profiles/<int:pk>/edit/", views.dashboard_profiles_edit, name="dashboard_profiles_edit"),
    path("dashboard/profiles/<int:pk>/delete/", views.dashboard_profiles_delete, name="dashboard_profiles_delete"),
    path("dashboard/providers/", views.dashboard_providers, name="dashboard_providers"),
    path("dashboard/provider-shifts/", views.dashboard_provider_shifts, name="dashboard_provider_shifts"),
    path("dashboard/provider-shifts/add/", views.dashboard_provider_shifts_add, name="dashboard_provider_shifts_add"),
    path(
        "dashboard/provider-shifts/<int:pk>/edit/",
        views.dashboard_provider_shifts_edit,
        name="dashboard_provider_shifts_edit",
    ),
    path(
        "dashboard/provider-shifts/<int:pk>/delete/",
        views.dashboard_provider_shifts_delete,
        name="dashboard_provider_shifts_delete",
    ),
    path("dashboard/providers/add/", views.dashboard_providers_add, name="dashboard_providers_add"),
    path("dashboard/providers/<int:pk>/edit/", views.dashboard_providers_edit, name="dashboard_providers_edit"),
    path("dashboard/providers/<int:pk>/delete/", views.dashboard_providers_delete, name="dashboard_providers_delete"),
    path("dashboard/feedback/", views.dashboard_feedback, name="dashboard_feedback"),
    path("dashboard/feedback/add/", views.dashboard_feedback_add, name="dashboard_feedback_add"),
    path("dashboard/feedback/<int:pk>/edit/", views.dashboard_feedback_edit, name="dashboard_feedback_edit"),
    path("dashboard/feedback/<int:pk>/delete/", views.dashboard_feedback_delete, name="dashboard_feedback_delete"),
    path("dashboard/users/", views.dashboard_users, name="dashboard_users"),
    path("dashboard/users/add/", views.dashboard_users_add, name="dashboard_users_add"),
    path("dashboard/users/<int:pk>/edit/", views.dashboard_users_edit, name="dashboard_users_edit"),
    path("dashboard/users/<int:pk>/delete/", views.dashboard_users_delete, name="dashboard_users_delete"),
    path("dashboard/support-tickets/", views.dashboard_support_tickets, name="dashboard_support_tickets"),
    path("dashboard/support-tickets/add/", views.dashboard_support_tickets_add, name="dashboard_support_tickets_add"),
    path(
        "dashboard/support-tickets/<int:pk>/edit/",
        views.dashboard_support_tickets_edit,
        name="dashboard_support_tickets_edit",
    ),
    path(
        "dashboard/support-tickets/<int:pk>/delete/",
        views.dashboard_support_tickets_delete,
        name="dashboard_support_tickets_delete",
    ),
    path("dashboard/faq/", views.dashboard_faq, name="dashboard_faq"),
    path("dashboard/faq/add/", views.dashboard_faq_add, name="dashboard_faq_add"),
    path("dashboard/faq/<int:pk>/edit/", views.dashboard_faq_edit, name="dashboard_faq_edit"),
    path("dashboard/faq/<int:pk>/delete/", views.dashboard_faq_delete, name="dashboard_faq_delete"),
    path(
        "dashboard/category-pages/",
        views.dashboard_service_category_pages,
        name="dashboard_service_category_pages",
    ),
    path(
        "dashboard/category-pages/add/",
        views.dashboard_service_category_pages_add,
        name="dashboard_service_category_pages_add",
    ),
    path(
        "dashboard/category-pages/<int:pk>/edit/",
        views.dashboard_service_category_pages_edit,
        name="dashboard_service_category_pages_edit",
    ),
    path(
        "dashboard/category-pages/<int:pk>/delete/",
        views.dashboard_service_category_pages_delete,
        name="dashboard_service_category_pages_delete",
    ),
    path(
        "dashboard/category-content-blocks/",
        views.dashboard_service_category_content_blocks,
        name="dashboard_service_category_content_blocks",
    ),
    path(
        "dashboard/category-content-blocks/add/",
        views.dashboard_service_category_content_blocks_add,
        name="dashboard_service_category_content_blocks_add",
    ),
    path(
        "dashboard/category-content-blocks/<int:pk>/edit/",
        views.dashboard_service_category_content_blocks_edit,
        name="dashboard_service_category_content_blocks_edit",
    ),
    path(
        "dashboard/category-content-blocks/<int:pk>/delete/",
        views.dashboard_service_category_content_blocks_delete,
        name="dashboard_service_category_content_blocks_delete",
    ),
    path(
        "dashboard/category-sections/",
        views.dashboard_service_category_sections,
        name="dashboard_service_category_sections",
    ),
    path(
        "dashboard/category-sections/add/",
        views.dashboard_service_category_sections_add,
        name="dashboard_service_category_sections_add",
    ),
    path(
        "dashboard/category-sections/<int:pk>/edit/",
        views.dashboard_service_category_sections_edit,
        name="dashboard_service_category_sections_edit",
    ),
    path(
        "dashboard/category-sections/<int:pk>/delete/",
        views.dashboard_service_category_sections_delete,
        name="dashboard_service_category_sections_delete",
    ),
    path(
        "dashboard/category-items/",
        views.dashboard_service_category_items,
        name="dashboard_service_category_items",
    ),
    path(
        "dashboard/category-items/add/",
        views.dashboard_service_category_items_add,
        name="dashboard_service_category_items_add",
    ),
    path(
        "dashboard/category-items/<int:pk>/edit/",
        views.dashboard_service_category_items_edit,
        name="dashboard_service_category_items_edit",
    ),
    path(
        "dashboard/category-items/<int:pk>/delete/",
        views.dashboard_service_category_items_delete,
        name="dashboard_service_category_items_delete",
    ),
    path(
        "dashboard/category-specs/",
        views.dashboard_service_category_specs,
        name="dashboard_service_category_specs",
    ),
    path(
        "dashboard/category-specs/add/",
        views.dashboard_service_category_specs_add,
        name="dashboard_service_category_specs_add",
    ),
    path(
        "dashboard/category-specs/<int:pk>/edit/",
        views.dashboard_service_category_specs_edit,
        name="dashboard_service_category_specs_edit",
    ),
    path(
        "dashboard/category-specs/<int:pk>/delete/",
        views.dashboard_service_category_specs_delete,
        name="dashboard_service_category_specs_delete",
    ),
    path(
        "dashboard/category-faq/",
        views.dashboard_service_category_faq,
        name="dashboard_service_category_faq",
    ),
    path(
        "dashboard/category-faq/add/",
        views.dashboard_service_category_faq_add,
        name="dashboard_service_category_faq_add",
    ),
    path(
        "dashboard/category-faq/<int:pk>/edit/",
        views.dashboard_service_category_faq_edit,
        name="dashboard_service_category_faq_edit",
    ),
    path(
        "dashboard/category-faq/<int:pk>/delete/",
        views.dashboard_service_category_faq_delete,
        name="dashboard_service_category_faq_delete",
    ),
    path("dashboard/service-pages/", views.dashboard_service_pages, name="dashboard_service_pages"),
    path("dashboard/service-pages/add/", views.dashboard_service_pages_add, name="dashboard_service_pages_add"),
    path(
        "dashboard/service-pages/<int:pk>/edit/",
        views.dashboard_service_pages_edit,
        name="dashboard_service_pages_edit",
    ),
    path(
        "dashboard/service-pages/<int:pk>/delete/",
        views.dashboard_service_pages_delete,
        name="dashboard_service_pages_delete",
    ),
    path(
        "dashboard/service-page-blocks/",
        views.dashboard_service_page_content_blocks,
        name="dashboard_service_page_content_blocks",
    ),
    path(
        "dashboard/service-page-blocks/add/",
        views.dashboard_service_page_content_blocks_add,
        name="dashboard_service_page_content_blocks_add",
    ),
    path(
        "dashboard/service-page-blocks/<int:pk>/edit/",
        views.dashboard_service_page_content_blocks_edit,
        name="dashboard_service_page_content_blocks_edit",
    ),
    path(
        "dashboard/service-page-blocks/<int:pk>/delete/",
        views.dashboard_service_page_content_blocks_delete,
        name="dashboard_service_page_content_blocks_delete",
    ),
    path(
        "dashboard/service-page-sections/",
        views.dashboard_service_page_sections,
        name="dashboard_service_page_sections",
    ),
    path(
        "dashboard/service-page-sections/add/",
        views.dashboard_service_page_sections_add,
        name="dashboard_service_page_sections_add",
    ),
    path(
        "dashboard/service-page-sections/<int:pk>/edit/",
        views.dashboard_service_page_sections_edit,
        name="dashboard_service_page_sections_edit",
    ),
    path(
        "dashboard/service-page-sections/<int:pk>/delete/",
        views.dashboard_service_page_sections_delete,
        name="dashboard_service_page_sections_delete",
    ),
    path(
        "dashboard/service-page-items/",
        views.dashboard_service_page_items,
        name="dashboard_service_page_items",
    ),
    path(
        "dashboard/service-page-items/add/",
        views.dashboard_service_page_items_add,
        name="dashboard_service_page_items_add",
    ),
    path(
        "dashboard/service-page-items/<int:pk>/edit/",
        views.dashboard_service_page_items_edit,
        name="dashboard_service_page_items_edit",
    ),
    path(
        "dashboard/service-page-items/<int:pk>/delete/",
        views.dashboard_service_page_items_delete,
        name="dashboard_service_page_items_delete",
    ),
    path(
        "dashboard/service-page-specs/",
        views.dashboard_service_page_specs,
        name="dashboard_service_page_specs",
    ),
    path(
        "dashboard/service-page-specs/add/",
        views.dashboard_service_page_specs_add,
        name="dashboard_service_page_specs_add",
    ),
    path(
        "dashboard/service-page-specs/<int:pk>/edit/",
        views.dashboard_service_page_specs_edit,
        name="dashboard_service_page_specs_edit",
    ),
    path(
        "dashboard/service-page-specs/<int:pk>/delete/",
        views.dashboard_service_page_specs_delete,
        name="dashboard_service_page_specs_delete",
    ),
    path(
        "dashboard/service-page-faq/",
        views.dashboard_service_page_faq,
        name="dashboard_service_page_faq",
    ),
    path(
        "dashboard/service-page-faq/add/",
        views.dashboard_service_page_faq_add,
        name="dashboard_service_page_faq_add",
    ),
    path(
        "dashboard/service-page-faq/<int:pk>/edit/",
        views.dashboard_service_page_faq_edit,
        name="dashboard_service_page_faq_edit",
    ),
    path(
        "dashboard/service-page-faq/<int:pk>/delete/",
        views.dashboard_service_page_faq_delete,
        name="dashboard_service_page_faq_delete",
    ),
    path("dashboard/invoices/", views.dashboard_invoices, name="dashboard_invoices"),
    path("dashboard/invoices/add/", views.dashboard_invoice_add, name="dashboard_invoice_add"),
    path("dashboard/invoices/<int:pk>/", views.dashboard_invoice_detail, name="dashboard_invoice_detail"),
    path("dashboard/invoices/<int:pk>/edit/", views.dashboard_invoice_edit, name="dashboard_invoice_edit"),
    path("dashboard/invoices/<int:pk>/pdf/", views.dashboard_invoice_pdf, name="dashboard_invoice_pdf"),
    path("dashboard/invoices/<int:pk>/send/", views.dashboard_invoice_send, name="dashboard_invoice_send"),
    path("dashboard/invoices/<int:pk>/paid/", views.dashboard_invoice_paid, name="dashboard_invoice_paid"),
    path("dashboard/invoices/<int:pk>/duplicate/", views.dashboard_invoice_duplicate, name="dashboard_invoice_duplicate"),
    path("dashboard/invoices/<int:pk>/credit/", views.dashboard_invoice_credit, name="dashboard_invoice_credit"),
    path("dashboard/zip-codes/", views.dashboard_zip_codes, name="dashboard_zip_codes"),
    path("dashboard/zip-codes/add/", views.dashboard_zip_codes_add, name="dashboard_zip_codes_add"),
    path(
        "dashboard/zip-codes/<int:pk>/edit/",
        views.dashboard_zip_codes_edit,
        name="dashboard_zip_codes_edit",
    ),
    path(
        "dashboard/zip-codes/<int:pk>/delete/",
        views.dashboard_zip_codes_delete,
        name="dashboard_zip_codes_delete",
    ),
    path(
        "dashboard/outside-area/",
        views.dashboard_outside_area_requests,
        name="dashboard_outside_area_requests",
    ),
    path(
        "dashboard/outside-area/add/",
        views.dashboard_outside_area_requests_add,
        name="dashboard_outside_area_requests_add",
    ),
    path(
        "dashboard/outside-area/<int:pk>/edit/",
        views.dashboard_outside_area_requests_edit,
        name="dashboard_outside_area_requests_edit",
    ),
    path(
        "dashboard/outside-area/<int:pk>/delete/",
        views.dashboard_outside_area_requests_delete,
        name="dashboard_outside_area_requests_delete",
    ),
    path("provider/dashboard/", views.provider_dashboard, name="provider_dashboard"),
    path("provider/orders/<int:pk>/", views.provider_order_detail, name="provider_order_detail"),
    path(
        "provider/service-bookings/<int:pk>/",
        views.provider_service_booking_detail,
        name="provider_service_booking_detail",
    ),
    path(
        "provider/service-bookings/<int:pk>/extend/",
        views.provider_service_booking_extend,
        name="provider_service_booking_extend",
    ),
    path(
        "provider/service-bookings/<int:pk>/status/",
        views.provider_service_booking_update_status,
        name="provider_service_booking_update_status",
    ),
    path(
        "provider/on-call-bookings/<int:pk>/",
        views.provider_on_call_booking_detail,
        name="provider_on_call_booking_detail",
    ),
    path("provider/orders/<int:pk>/status/", views.provider_update_status, name="provider_update_status"),
    path("consultation-booking/step-1/", views.booking_step_1, name="booking_step_1"),
    path("consultation-booking/step-2/", views.booking_step_2, name="booking_step_2"),
    path("consultation-booking/step-3/", views.booking_step_3, name="booking_step_3"),
    path("consultation-booking/step-4/", views.booking_step_4, name="booking_step_4"),
    path("consultation-booking/step-5/", views.booking_step_5, name="booking_step_5"),
    path("consultation-booking/step-6/", views.booking_step_6, name="booking_step_6"),
    path("consultation-booking/step-7/", views.booking_step_7, name="booking_step_7"),
    path("consultation-booking/thank-you/", views.booking_thank_you, name="booking_thank_you"),
    path("booking/step-<int:step>/", views.legacy_consultation_booking_step, name="legacy_booking_step"),
    path("booking/thank-you/", views.legacy_consultation_booking_thank_you, name="legacy_booking_thank_you"),
    path("book-electrician/step-<int:step>/", views.electrician_booking_step, name="electrician_booking_step"),
    path("book-electrician/thank-you/", views.electrician_booking_thank_you, name="electrician_booking_thank_you"),
    path("service-booking/step-<int:step>/", views.service_booking_step, name="service_booking_step"),
    path("service-booking/slots/", views.service_booking_slots, name="service_booking_slots"),
    path("service-booking/<int:pk>/calendar/", views.service_booking_calendar, name="service_booking_calendar"),
    path("on-call-booking/step-<int:step>/", views.on_call_booking_step, name="on_call_booking_step"),
]
