XBBBB BBBBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXX
          XXXXXXXX XXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXX XXX XXXXXXXXXX XXXX X XXXXXXXXXX
        XXXXX
      XXXXXX
    XXXXXXXX

    XXXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX
        XXXXX
          XXXXXXXXXXXX XXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXX XXX XXXXX XXXXXXXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
      XXXXXX

      XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXX
          XXXXXX
          BBB BBBBBBB BB BBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXX
              XXXXXXFFFFFFFFFFF FFFFFFFFFFXXXXXXX
              XXXXXXFFFFFFFFFFFXXXXXXX
              XXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBXXXXXXXXXX
              XXXXXXX
            XXXXXX
          BBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXX
          BBBBBB
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXX
          XXXXXX
          BBB BBBBBBB BB BBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXX
              XXXXXXFFFFFFFFFFF FFFFFFFFFFXXXXXXX
              XXXXXXFFFFFFFFFFFXXXXXXX
              XXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBXXXXXXXXXX
              XXXXXXX
            XXXXXX
          BBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX
          BBBBBB
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXX
          XXXXXX
          BBB BBBBBBB BB BBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXX
              XXXXXXFFFFFFFFFFFXXXXXXX
              XXXXXXFFFFFFFFFFFXXXXXXX
              XXXXXXFFFFFFFFFFFXXXXXXX
              XXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBXXXXXXXXXX
              XXXXXXX
            XXXXXX
          BBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX
          BBBBBB
        XXXXXX
      XXXXXXXXXX
    XXXXXXX
  XXXXXX

  XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
        XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXX
        XXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX
    XXX
  XXXXXXXXX
XXXXXXX
XXXXXXX
