XBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB BBBB

BBBBB BBBBB gettext(u'Book an Electrician') BBBBBBBB
BBBBB BBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXBBBBBBBB

BBBBB BBBBBBBBBB
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
BBBBBBBB

BBBBB BBBBBBB
  XXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Progress') XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Step %(step)s of 8') SSSS SSSSSSSS SS S
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXX XXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXX BB BBBB BB BXXXXXXXXXBBBBBXX
            XXXXXXXXXXXXXX
            XXXXX gettext(u'Service') XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXX BB BBBB BB B BB BBBB BB BXXXXXXXXXBBBBBXX
            XXXXXXXXXXXXXX
            XXXXX gettext(u'Date & Time') XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXX BB BBBB BB BXXXXXXXXXBBBBBXX
            XXXXXXXXXXXXXX
            XXXXX gettext(u'Location') XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXX BB BBBB BB BXXXXXXXXXBBBBBXX
            XXXXXXXXXXXXXX
            XXXXX gettext(u'Details') XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX

      BB BBBBBB
        XXXX XXXXXXXXXXXXXXXXXX
          XXXXXXXX gettext(u'Please review the following:') XXXXXXXXX
          XXXX
            BBB BBB BB BBBBBB
              XXXXXXXXX
            BBBBBB
          XXXXX
        XXXXXX
      BBBBB

      BBBBB BBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
  XXXXXXX
BBBBBBBB

BBBBB BBBBBBBB
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
BBBBBBBB
