XBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
  BBBBBBBBBB

  XXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
        XXXX gettext(u'Additional notes') XXXXX
        XXX gettext(u'Optional details that may help the electrician prepare.') XXXX
      XXXXXX
    XXXXXX

    XXXXXX XXXXXXXXXXXXXXXXX gettext(u'Notes') XXXXXXXX

    XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXX
              XXXXXXXXXXXXX gettext(u'Any extra details, preferences, or constraints...') XX
        FFFFFFFFFF
    XXXXXXXXXXX
  XXXXXXXXXX

  XXXX XXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXX XXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BXX
         gettext(u'Back') 
    XXXX

    XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
         gettext(u'Continue to Step 6 ->') 
    XXXXXXXXX
  XXXXXX
XXXXXXX
BBBBBBBB
