XBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
  BBBBBBBBBB
  XXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
        XXXX gettext(u'How many hours do you want to book?') XXXXX
        XXX gettext(u'Select an initial duration for your professional service.') XXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX BB BBBBBBBBBB BB BBB BB BBBBBBBBBB BB BXXXXXXXBBBBBX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Hour') XXXXXXX
      XXXXXXXX

      XXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX BB BBBBBBBBBB BB BBB BB BBBBBBBBBB BB BXXXXXXXBBBBBX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Hours') XXXXXXX
      XXXXXXXX

      XXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX BB BBBBBBBBBB BB BBB BB BBBBBBBBBB BB BXXXXXXXBBBBBX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Hours') XXXXXXX
      XXXXXXXX

      XXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX BB BBBBBBBBBB BB BBB BB BBBBBBBBBB BB BXXXXXXXBBBBBX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Hours') XXXXXXX
      XXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXX
      XXXXXXXX gettext(u'Proactive Notice:') XXXXXXXXX
       gettext(u'Booked hours are an estimate. Final cost is adjusted based on actual time spent on site to ensure you only pay for what you need.') 
    XXXXXX
  XXXXXXXXXX

  XXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
        XXXX gettext(u'Describe the work') XXXXX
        XXX gettext(u'Provide as much detail as possible to help us prepare.') XXXX
      XXXXXX
    XXXXXX

    XXXXXX XXXXXXXXXXXXXXXXX gettext(u'Project scope') XXXXXXXX
    XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXX
              XXXXXXXXXXXXX gettext(u'Tell us what needs to be done (e.g., install ceiling fans, fix circuit breaker...)') XXFFFFFFFFFFXXXXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXX
       gettext(u'Incomplete information may affect time and price.') 
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXX
      XXXXX
        XXXXXX XXXXXXXXXXXXXXXXX gettext(u'Property type') XXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBXXXXXXXBBBBBX
            XXXXXX gettext(u'Residential Property') XXXXXXX
          XXXXXXXX

          XXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBXXXXXXXBBBBBX
            XXXXXX gettext(u'Commercial Space') XXXXXXX
          XXXXXXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Logistics') XXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBXXXXXXXBBBBBX
          XXXXXX gettext(u'I confirm that the service professional will have full access to the work area at the scheduled time.') XXXXXXX
        XXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXXXXXX

  XXXX XXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXX XXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBXX gettext(u'Back') XXXX
    XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
       gettext(u'Continue to Step 2 ->') 
    XXXXXXXXX
  XXXXXX
XXXXXXX
BBBBBBBB
