XBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
  BBBBBBBBBB

  XXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
        XXXX gettext(u'Where is the work located?') XXXXX
        XXX gettext(u'Provide the job site address so we can plan the visit.') XXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXX gettext(u'Street Address') XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXX gettext(u'e.g. 123 Artisan Street') X
               XXXXXXXFFFFFFFFFFXX
      XXXXXX

      XXXXX
        XXXXXX XXXXXXXXXXXXXXXXX gettext(u'Postal Code') XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXX
               XXXXXXXXXXXXX gettext(u'XXXXX') X
               XXXXXXXFFFFFFFFFFXX
      XXXXXX

      XXXXX
        XXXXXX XXXXXXXXXXXXXXXXX gettext(u'City') XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXX
               XXXXXXXXXXXXX gettext(u'City Name') X
               XXXXXXXFFFFFFFFFFXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXX
      XXXXXXXX gettext(u'Please note:') XXXXXXXXX
       gettext(u'Ensure the address is accurate to avoid scheduling delays. Incorrect addresses or locations outside our service area may incur additional travel fees.') 
    XXXXXX
  XXXXXXXXXX

  XXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
        XXXX gettext(u'Customer type') XXXXX
        XXX gettext(u'Select who is booking this service.') XXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBXXXXXXXBBBBBX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Private individual') XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Personal home services and residential repairs.') XXXXXX
        XXXXXX
      XXXXXXXX

      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBBXXXXXXXBBBBBX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Business') XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Commercial or organization bookings.') XXXXXX
        XXXXXX
      XXXXXXXX
    XXXXXX
  XXXXXXXXXX

  XXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
        XXXX gettext(u'Your contact details') XXXXX
        XXX gettext(u'We will send updates to this information.') XXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXX gettext(u'Full Name') XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXX
               XXXXXXXXXXXXX gettext(u'John Doe') X
               XXXXXXXFFFFFFFFFFXX
      XXXXXX

      XXXXX
        XXXXXX XXXXXXXXXXXXXXXXX gettext(u'Phone Number') XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXX
               XXXXXXXXXXXXX gettext(u'+1 (555) 000-0000') X
               XXXXXXXFFFFFFFFFFXX
      XXXXXX

      XXXXX
        XXXXXX XXXXXXXXXXXXXXXXX gettext(u'Email Address') XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXX
               XXXXXXXXXXXXX gettext(u'john@example.com') X
               XXXXXXXFFFFFFFFFFXX
      XXXXXX
    XXXXXX

    XXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBXXXXXXXBBBBBX
      XXXXXX gettext(u'I confirm these contact details are correct. I understand that communication regarding this booking will be sent to the email provided.') XXXXXXX
    XXXXXXXX
  XXXXXXXXXX

  XXXX XXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXX XXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BXX gettext(u'Back') XXXX
    XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Continue to Step 4 ->') XXXXXXXXX
  XXXXXX
XXXXXXX
BBBBBBBB
