XBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
  BBBBBBBBBB

  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
      XXXX gettext(u'Complete Your Booking') XXXXX
      XXX gettext(u'Finalize your schedule and confirm the details below.') XXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Step 6-8 of 8') XXXXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX

      XXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
            XXXX gettext(u'Preferred Date & Time') XXXXX
            XXX gettext(u'Select date and arrival window.') XXXX
          XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
            XXXX XXXXXXXXXXXXXXXXX gettext(u'Select Date') XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXFFFFFFFFFFXXXXXXXX
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                   XXXXXXXFFFFFFFFFFXX
          XXXXXX

          XXXXX
            XXXX XXXXXXXXXXXXXXXXX gettext(u'Arrival Window') XXXXXX

            XXXX XXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXX
                       XXXXXXXXXXXXXXXXXXXXX
                       XXXXXXXXXXXXXX XXXXXX XX X XXXXX XXXX
                       BB BBBBBBBBBBBBBBBBBBB BB BBBBBBBB BBBBBB BB B BBBBB BBBBXXXXXXXBBBBBX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Morning') XXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X XXXXX XXXXXXXX
                XXXXXX
              XXXXXXXX

              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXX
                       XXXXXXXXXXXXXXXXXXXXX
                       XXXXXXXXXXXXXXXX XXXXXX XX X XXXXX XXXX
                       BB BBBBBBBBBBBBBBBBBBB BB BBBBBBBBBB BBBBBB BB B BBBBB BBBBXXXXXXXBBBBBX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Afternoon') XXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X XXXXX XXXXXXXX
                XXXXXX
              XXXXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXXXXXX

      XXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
            XXXX gettext(u'Pricing Transparency') XXXXX
            XXX gettext(u'Estimated cost calculation.') XXXX
          XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXX gettext(u'Minimum Callout Fee (1st hr)') XXXXXXX
            XXXXXXXX FFFFFFFFFFFFFXXXXXXXXX
          XXXXXX

          XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXX
               gettext(u'\n              Estimated Additional Time (%(hours)s hrs x %(currency)s %(rate)s/hr)\n              ') 
              SSSSSSSSS SSSSSSSSSS SSSS SSSSSSSSSS SSS S SSSSSSSSSSSS SSSSSSSSSSSS
              
            XXXXXXX
            XXXXXXXX FFFFFFFFFFFFFXXXXXXXXX
          XXXXXX

          XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX gettext(u'Total Estimated Booking') XXXXXXX
            XXXXXXXX FFFFFFFFFFFFFXXXXXXXXX
          XXXXXX
        XXXXXX

        XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXX
                 BB BBBBBBBBBBBBBBBBXXXXXXXBBBBBX
          XXXXXX
             gettext(u'I understand this is an estimate. Final pricing is based on actual time spent on site and any material costs incurred.') 
          XXXXXXX
        XXXXXXXX
      XXXXXXXXXX
    XXXXXX

    XXXXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Review & Confirm') XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Service type') XXXXXXX
          XXXXXXXXFFFFFFFFFFFFFFFFFFFF FFFFFFFFFF FFFFFFFFFFFFXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Location') XXXXXXX
          XXXXXXXXFFFFFFFFFFFFF FFFFFFF FFFFX FFFFFFFFFFFFFFF FFFFFFFFXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Appointment') XXXXXXX
          XXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXX XXX XBBBBB
            BB BBBBBBBBBBBBBBBBBBB X BBBB X X XX X XX XXBBBBB
          XXXXXXXXX
        XXXXXX

        XXXXXX XXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
          XXXXXX gettext(u'I confirm all the provided information above is correct.') XXXXXXX
        XXXXXXXX

        XXXXXX XXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
          XXXXXX
             gettext(u'I accept the') 
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXX gettext(u'Terms of Service') XXXX
             gettext(u'and') 
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBXX gettext(u'Cancellation Policy') XXXXX
          XXXXXXX
        XXXXXXXX

        XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
           gettext(u'Confirm Booking ->') 
        XXXXXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXX
           gettext(u'No immediate charge will be made to your card.') 
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Need help with your booking?') XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Call')  XXXXX XXXXXXXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXX XXXXXXXXXX
       XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BXX
        gettext(u'Back') 
    XXXX
  XXXXXX
XXXXXXX
BBBBBBBB
