XBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
  BBBBBBBBBB

  XXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
        XXXX gettext(u'Preferred Date & Time') XXXXX
        XXX gettext(u'Select the best time for your visit.') XXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
        XXXX XXXXXXXXXXXXXXXXX gettext(u'Select Date') XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXFFFFFFFFFFXXXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFFXX
      XXXXXX

      XXXXX
        XXXX XXXXXXXXXXXXXXXXX gettext(u'Arrival Window') XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXX XXXXXX XX X XXXXX XXXX
                   BB BBBBBBBBBBBBBBBBBBB BB BBBBBBBB BBBBBB BB B BBBBB BBBBXXXXXXXBBBBBX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Morning') XXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'08:00 AM - 12:00 PM') XXXXXX
            XXXXXX
          XXXXXXXX

          XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXX XXXXXX XX X XXXXX XXXX
                   BB BBBBBBBBBBBBBBBBBBB BB BBBBBBBBBB BBBBBB BB B BBBBB BBBBXXXXXXXBBBBBX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Afternoon') XXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'12:00 PM - 05:00 PM') XXXXXX
            XXXXXX
          XXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXXXXXX

  XXXX XXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXX XXXXXXXXXX
       XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BXX
         gettext(u'Back') 
    XXXX

    XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
         gettext(u'Continue to Step 7 ->') 
    XXXXXXXXX
  XXXXXX
XXXXXXX
BBBBBBBB
