XBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
  BBBBBBBBBB

  XXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
        XXXX gettext(u'Pricing Transparency') XXXXX
        XXX gettext(u'Review the estimated cost calculation.') XXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX gettext(u'Minimum Callout Fee (1st hr)') XXXXXXX
        XXXXXXXX FFFFFFFFFFFFFXXXXXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX
           gettext(u'\n          Estimated Additional Time (%(hours)s hrs x %(currency)s %(rate)s/hr)\n          ') 
          SSSSSSSSS SSSSSSSSSS SSSS SSSSSSSSSS SSS S SSSSSSSSSSSS SSSSSSSSSSSS
          
        XXXXXXX
        XXXXXXXX FFFFFFFFFFFFFXXXXXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX gettext(u'Total Estimated Booking') XXXXXXX
        XXXXXXXX FFFFFFFFFFFFFXXXXXXXXX
      XXXXXX
    XXXXXX

    XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXX
             XXXXXXXXXXX
             BB BBBBBBBBBBBBBBBBXXXXXXXBBBBBX
      XXXXXX
         gettext(u'I understand this is an estimate. Final pricing is based on actual time spent on site and any material costs incurred.') 
      XXXXXXX
    XXXXXXXX
  XXXXXXXXXX

  XXXX XXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXX XXXXXXXXXX
       XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BXX
        gettext(u'Back') 
    XXXX

    XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
         gettext(u'Continue to Step 8 ->') 
    XXXXXXXXX
  XXXXXX
XXXXXXX
BBBBBBBB
