XBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
  BBBBBBBBBB

  XXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
        XXXX gettext(u'Access & preparation') XXXXX
        XXX gettext(u'Help us prepare for a smooth appointment.') XXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXX gettext(u'Access notes') XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXX gettext(u'Gate code, concierge, or access instructions') X
               XXXXXXXFFFFFFFFFFXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXX gettext(u'Parking details') XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXX gettext(u'Parking availability or restrictions') X
               XXXXXXXFFFFFFFFFFXX
      XXXXXX
    XXXXXX
  XXXXXXXXXX

  XXXX XXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXX XXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BXX gettext(u'Back') XXXX
    XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Continue to Step 5 ->') XXXXXXXXX
  XXXXXX
XXXXXXX
BBBBBBBB
