XBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
  BBBBBBBBBB

  XXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
        XXXX gettext(u'Select the service type') XXXXX
        XXX gettext(u'Choose the category that best matches your booking.') XXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBXXXXXXXBBBBBX
        XXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Residential Electrical Repair') XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Troubleshooting, outlets, lighting, and home upgrades.') 
          XXXXXX
        XXXXXX
      XXXXXXXX

      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBXXXXXXXBBBBBX
        XXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'New Installations') XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Panels, circuits, EV chargers, and appliance hookups.') 
          XXXXXX
        XXXXXX
      XXXXXXXX

      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBXXXXXXXBBBBBX
        XXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Commercial Maintenance') XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Offices, retail, and property maintenance support.') 
          XXXXXX
        XXXXXX
      XXXXXXXX
    XXXXXX
  XXXXXXXXXX

  XXXX XXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXX XXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BXX
       gettext(u'Back') 
    XXXX
    XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
       gettext(u'Continue to Step 3 ->') 
    XXXXXXXXX
  XXXXXX
XXXXXXX
BBBBBBBB
