BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
  BBBBBBBBBB

  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX gettext(u'Enterprise Grade') XXXXXX
    XXXX
       gettext(u'On-Call Electrical Service') 
      XXXXXXX gettext(u'Jour') XXXXXXXX
    XXXXX
    XXX
       gettext(u'Priority access to a licensed electrician for urgent electrical issues. Available through a service agreement for businesses, property owners, and housing associations.') 
    XXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX

      XXXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX gettext(u'When do you need on-call coverage?') XXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX

          XXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBXXXXXXXBBBBBX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Business hours') XXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Standard operations 08:00 - 17:00') XXXXXXX
            XXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXX

          XXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX BB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBXXXXXXXBBBBBX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Evenings') XXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Extended coverage 17:00 - 22:00') XXXXXXX
            XXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXX

          XXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX BB BBBBBBBB BB BBBBBBBBBBBBBBBBBBBXXXXXXXBBBBBX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Nights') XXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Late shift 22:00 - 08:00') XXXXXXX
            XXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXX

          XXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX BB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBXXXXXXXBBBBBX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Weekends & holidays') XXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'24/7 during non-business days') XXXXXXX
            XXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXX

        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX gettext(u'How quickly do you need a response?') XXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX

          XXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBXXXXXXXBBBBBX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Standard response') XXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Service response within 4-8 hours of the reported incident.') XXXXXXX
            XXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXX

          XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBXXXXXXXBBBBBX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Premium') XXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Priority response') XXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Guaranteed technician on-site within 1-2 hours 24/7.') XXXXXXX
            XXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXX

        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX gettext(u'What should the on-call service cover?') XXXXX
        XXXX XXXXXXXXXXXXXXXXXX

          XXXXXX XXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBXXXXXXXBBBBBX
            XXXXXX gettext(u'Power outages') XXXXXXX
          XXXXXXXX

          XXXXXX XXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBXXXXXXXBBBBBX
            XXXXXX gettext(u'Fuse boards') XXXXXXX
          XXXXXXXX

          XXXXXX XXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBXXXXXXXBBBBBX
            XXXXXX gettext(u'Common areas') XXXXXXX
          XXXXXXXX

          XXXXXX XXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBXXXXXXXBBBBBX
            XXXXXX gettext(u'Critical systems') XXXXXXX
          XXXXXXXX

          XXXXXX XXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBXXXXXXXBBBBBX
            XXXXXX gettext(u'General faults') XXXXXXX
          XXXXXXXX

        XXXXXX
      XXXXXX

    XXXXXX

    XXXXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Service Summary') XXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXX gettext(u'Coverage Type') XXXXXXX
        XXXXXXXX gettext(u'B2B Service Agreement') XXXXXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXX gettext(u'Location') XXXXXXX
        XXXXXXXX gettext(u'Greater Stockholm') XXXXXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXX
         gettext(u'Final pricing and conditions are subject to technical audit and individual facility complexity.') 
      XXXXXX

      XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX
         gettext(u'Apply for On-Call Service')  X
      XXXXXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
         gettext(u'Technicians available now') 
      XXXXXX
    XXXXXXXX

  XXXXXX
XXXXXXX
BBBBBBBB
