BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
  BBBBBBBBBB

  XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Registration Flow') XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Property & Risk Profile') XXXXXX
    XXX gettext(u'Tell us about the physical infrastructure we’ll be supporting.') XXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX

      XXXX XXXXXXXXXXXXX
        XXXXXXX gettext(u'Property Type') XXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXX gettext(u'Select property type') XXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBXXXXXXXXBBBBBX
             gettext(u'Commercial') 
          XXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBXXXXXXXXBBBBBX
             gettext(u'Industrial') 
          XXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXXXBBBBBX
             gettext(u'Mixed Use') 
          XXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBXXXXXXXXBBBBBX
             gettext(u'Residential') 
          XXXXXXXXX
        XXXXXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXX
        XXXXXXX gettext(u'Number of Assets/Properties') XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXX gettext(u'e.g. 12') X
               XXXXXXXFFFFFFFFFFXX
      XXXXXX

      XXXX XXXXXXXXXXXXX
        XXXXXXX gettext(u'Primary City / Region') XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXX gettext(u'Search region...') X
               XXXXXXXFFFFFFFFFFXX
      XXXXXX

    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXX
      XXXXX
        XXXXXXXX gettext(u'Shared Critical Systems') XXXXXXXXX
        XXX gettext(u'Are HVAC, plumbing, or electrical systems shared?') XXXX
      XXXXXX
      XXXXXX XXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXBBBBBX
        XXXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXX
    XXXXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXX XXXXXXXXXX
       XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BXX
        gettext(u'Back') 
    XXXX

    XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
       gettext(u'Review & Finalize') 
    XXXXXXXXX
  XXXXXX

XXXXXXX
BBBBBBBB
