BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB BBBB
BBBBB BBBBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
  BBBBBBBBBB

  XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Registration Progress') XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Who is applying?') XXXXXX
    XXX
       gettext(u'Select the entity type for your registration.') 
      XXXXXXXX gettext(u'Note:') XXXXXXXXX
       gettext(u'Our smart on-call service is available for professional entities only. Private individuals are not eligible.') 
    XXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXX

    XXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBB BB BBBBBBBBBBXXXXXXXBBBBBX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX gettext(u'Business / Organization') X XXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX gettext(u'Business / Organization') XXXXX
        XXX gettext(u'For corporate entities and startups.') XXXX
      XXXXXX
    XXXXXXXX

    XXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBB BB BBBBBBBBBXXXXXXXBBBBBX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX gettext(u'Housing Association') X XXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX gettext(u'Housing Association') XXXXX
        XXX gettext(u'For property owners and co-ops.') XXXX
      XXXXXX
    XXXXXXXX

  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Organization Information') XXXXXX

    XXXX XXXXXXXXXXXXXXXXXX

      XXXXX
        XXXXXXX gettext(u'Organization Name') XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'e.g. Acme Corp') X XXXXXXXFFFFFFFFFFXX
      XXXXXX

      XXXXX
        XXXXXXX gettext(u'Org Number') XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'556XXX-XXXX') X XXXXXXXFFFFFFFFFFXX
      XXXXXX

      XXXXX
        XXXXXXX gettext(u'Contact Person') XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Full Name') X XXXXXXXFFFFFFFFFFXX
      XXXXXX

      XXXXX
        XXXXXXX gettext(u'Phone Number') XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'+46 00 000 00 00') X XXXXXXXFFFFFFFFFFXX
      XXXXXX

      XXXX XXXXXXXXXXXXX
        XXXXXXX gettext(u'Email Address') XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'contact@organization.com') X XXXXXXXFFFFFFFFFFXX
      XXXXXX

    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Address Details') XXXXXX

    XXXX XXXXXXXXXXXXXXXXXX

      XXXX XXXXXXXXXXXXX
        XXXXXXX gettext(u'Company Address') XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Street Name 123') X XXXXXXXFFFFFFFFFFXX
      XXXXXX

      XXXXX
        XXXXXXX gettext(u'ZIP Code') XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'123 45') X XXXXXXXFFFFFFFFFFXX
      XXXXXX

      XXXXX
        XXXXXXX gettext(u'City') XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Stockholm') X XXXXXXXFFFFFFFFFFXX
      XXXXXX

    XXXXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXX XXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BXX
       gettext(u'Back') 
    XXXX

    XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
       gettext(u'Continue to Next Step')  X
    XXXXXXXXX
  XXXXXX

XXXXXXX
BBBBBBBB
