BBBB BBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Notice') XXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       gettext(u'This website is in active development. Some features may be updated or refined.') 
    XXXXXXX
  XXXXXX
XXXXXX
