# Generated by Django 4.2.28 on 2026-02-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0002_add_bullet_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_type', models.CharField(blank=True, max_length=40)),
                ('property_type', models.CharField(blank=True, max_length=40)),
                ('property_size', models.CharField(blank=True, max_length=40)),
                ('year_built', models.CharField(blank=True, max_length=10)),
                ('services', models.JSONField(blank=True, default=list)),
                ('urgent', models.BooleanField(default=False)),
                ('project_description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='electricity/booking/photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='electricity/booking/videos/')),
                ('document', models.FileField(blank=True, null=True, upload_to='electricity/booking/docs/')),
                ('contact_type', models.CharField(blank=True, choices=[('private', 'Private'), ('business', 'Business')], max_length=20)),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('availability_days', models.JSONField(blank=True, default=list)),
                ('time_window', models.CharField(blank=True, choices=[('morning', 'Morning'), ('midday', 'Midday'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=20)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time_slot', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
