# Generated by Django 4.2.28 on 2026-02-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0003_consultationbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationbooking',
            name='property_type_other',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
