# Generated by Django 4.2.28 on 2026-02-05 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('electricity', '0004_consultationbooking_property_type_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationbooking',
            name='company_address',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='consultationbooking',
            name='company_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='consultationbooking',
            name='organization_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='consultationbooking',
            name='personal_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('private', 'Private'), ('business', 'Business')], default='private', max_length=20)),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('street_address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='Germany', max_length=60)),
                ('property_type', models.CharField(blank=True, max_length=40)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('personal_id', models.CharField(blank=True, max_length=40)),
                ('company_name', models.CharField(blank=True, max_length=160)),
                ('organization_number', models.CharField(blank=True, max_length=40)),
                ('company_address', models.CharField(blank=True, max_length=220)),
                ('accepted_terms', models.BooleanField(default=False)),
                ('accepted_privacy', models.BooleanField(default=False)),
                ('marketing_opt_in', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
