# Generated by Django 4.2.28 on 2026-02-08 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0014_oncallbooking_assigned_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('scheduled', 'Scheduled'), ('on_the_way', 'On the way'), ('started', 'Started'), ('paused', 'Paused'), ('resumed', 'Resumed'), ('completed', 'Completed'), ('not_available', 'Arrived but customer not available'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ServiceBookingStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('scheduled', 'Scheduled'), ('on_the_way', 'On the way'), ('started', 'Started'), ('paused', 'Paused'), ('resumed', 'Resumed'), ('completed', 'Completed'), ('not_available', 'Arrived but customer not available'), ('canceled', 'Canceled')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='electricity.servicebooking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
