# Generated by Django 4.2.28 on 2026-02-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0015_alter_servicebooking_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedZipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestOutsideArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('zip_code', models.CharField(max_length=10)),
                ('request_type', models.CharField(choices=[('consultation', 'Consultation Booking'), ('service', 'Service Booking'), ('on_call', 'On-Call Booking')], max_length=20)),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
