# Generated by Django 4.2.28 on 2026-02-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0017_service_booking_time_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationbooking',
            name='consultation_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='consultationbooking',
            name='is_first_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oncallbooking',
            name='emergency_hours',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='oncallbooking',
            name='estimated_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='oncallbooking',
            name='hourly_rate_emergency_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='fixed_services_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='hourly_hours',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='hourly_rate_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='pricing_type',
            field=models.CharField(choices=[('hourly', 'Hourly electrician'), ('fixed', 'Fixed service price')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='servicepricing',
            name='consultation_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicepricing',
            name='hourly_rate_electrician',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicepricing',
            name='hourly_rate_emergency',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
