# Generated by Django 4.2.28 on 2026-02-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0018_consultationbooking_consultation_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricianBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('private', 'Private Customer'), ('business', 'Business / Organization')], max_length=20)),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('street_address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('property_type', models.CharField(blank=True, max_length=60)),
                ('work_description', models.TextField(blank=True)),
                ('access_notes', models.CharField(blank=True, max_length=200)),
                ('parking_info', models.CharField(blank=True, max_length=200)),
                ('additional_notes', models.TextField(blank=True)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('arrival_window', models.CharField(blank=True, max_length=80)),
                ('hours', models.PositiveIntegerField(default=1)),
                ('hourly_rate_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estimated_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='SEK', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
