# Generated by Django 4.2.28 on 2026-02-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0021_faqentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='message_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='message_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='message_sv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='electricalservice',
            name='bullet_points_ar',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='electricalservice',
            name='bullet_points_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='electricalservice',
            name='bullet_points_sv',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='electricalservice',
            name='short_description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='electricalservice',
            name='short_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='electricalservice',
            name='short_description_sv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='electricalservice',
            name='title_ar',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='electricalservice',
            name='title_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='electricalservice',
            name='title_sv',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='faqentry',
            name='answer_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faqentry',
            name='answer_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faqentry',
            name='answer_sv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faqentry',
            name='question_ar',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='faqentry',
            name='question_en',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='faqentry',
            name='question_sv',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='servicepricing',
            name='name_ar',
            field=models.CharField(default='Default Pricing', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='servicepricing',
            name='name_en',
            field=models.CharField(default='Default Pricing', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='servicepricing',
            name='name_sv',
            field=models.CharField(default='Default Pricing', max_length=120, null=True),
        ),
    ]
