# Generated by Django 4.2.28 on 2026-02-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0022_adminnotification_message_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricalservice',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='electricalservice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
