# Generated by Django 4.2.28 on 2026-03-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0025_electricianbooking_transport_fee_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricianbooking',
            name='rot_percent_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='electricianbooking',
            name='rot_requested',
            field=models.BooleanField(default=False),
        ),
    ]
