# Generated by Django 4.2.28 on 2026-05-31 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0031_servicedetailpage_servicedetailspecrow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategoryContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.CharField(choices=[('text', 'Text only'), ('split_image_right', 'Text with image right'), ('split_image_left', 'Text with image left'), ('emphasis', 'Emphasis band'), ('checklist', 'Checklist panel')], default='text', max_length=24)),
                ('eyebrow', models.CharField(blank=True, max_length=120)),
                ('eyebrow_en', models.CharField(blank=True, max_length=120, null=True)),
                ('eyebrow_ar', models.CharField(blank=True, max_length=120, null=True)),
                ('eyebrow_sv', models.CharField(blank=True, max_length=120, null=True)),
                ('title', models.CharField(max_length=160)),
                ('title_en', models.CharField(max_length=160, null=True)),
                ('title_ar', models.CharField(max_length=160, null=True)),
                ('title_sv', models.CharField(max_length=160, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('subtitle_en', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitle_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitle_sv', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField(blank=True)),
                ('body_en', models.TextField(blank=True, null=True)),
                ('body_ar', models.TextField(blank=True, null=True)),
                ('body_sv', models.TextField(blank=True, null=True)),
                ('secondary_body', models.TextField(blank=True)),
                ('secondary_body_en', models.TextField(blank=True, null=True)),
                ('secondary_body_ar', models.TextField(blank=True, null=True)),
                ('secondary_body_sv', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='electricity/category_pages/blocks/')),
                ('image_alt', models.CharField(blank=True, max_length=160)),
                ('image_alt_en', models.CharField(blank=True, max_length=160, null=True)),
                ('image_alt_ar', models.CharField(blank=True, max_length=160, null=True)),
                ('image_alt_sv', models.CharField(blank=True, max_length=160, null=True)),
                ('badge', models.CharField(blank=True, max_length=80)),
                ('badge_en', models.CharField(blank=True, max_length=80, null=True)),
                ('badge_ar', models.CharField(blank=True, max_length=80, null=True)),
                ('badge_sv', models.CharField(blank=True, max_length=80, null=True)),
                ('list_title', models.CharField(blank=True, max_length=80)),
                ('list_title_en', models.CharField(blank=True, max_length=80, null=True)),
                ('list_title_ar', models.CharField(blank=True, max_length=80, null=True)),
                ('list_title_sv', models.CharField(blank=True, max_length=80, null=True)),
                ('list_lines', models.TextField(blank=True, default='')),
                ('list_lines_en', models.TextField(blank=True, default='', null=True)),
                ('list_lines_ar', models.TextField(blank=True, default='', null=True)),
                ('list_lines_sv', models.TextField(blank=True, default='', null=True)),
                ('stat_label', models.CharField(blank=True, max_length=80)),
                ('stat_label_en', models.CharField(blank=True, max_length=80, null=True)),
                ('stat_label_ar', models.CharField(blank=True, max_length=80, null=True)),
                ('stat_label_sv', models.CharField(blank=True, max_length=80, null=True)),
                ('stat_value', models.CharField(blank=True, max_length=80)),
                ('stat_value_en', models.CharField(blank=True, max_length=80, null=True)),
                ('stat_value_ar', models.CharField(blank=True, max_length=80, null=True)),
                ('stat_value_sv', models.CharField(blank=True, max_length=80, null=True)),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('cta_label_en', models.CharField(blank=True, max_length=80, null=True)),
                ('cta_label_ar', models.CharField(blank=True, max_length=80, null=True)),
                ('cta_label_sv', models.CharField(blank=True, max_length=80, null=True)),
                ('cta_url', models.CharField(blank=True, max_length=240)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='electricity.servicecategorypage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
