# Generated by Django 4.2.28 on 2026-05-31 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0033_servicedetailcontentblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategorycontentblock',
            name='target_service_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_content_blocks', to='electricity.servicedetailpage'),
        ),
    ]
