# Generated by Django 4.2.28 on 2026-06-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0035_customerfeedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategorypage',
            name='spec_col_5',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='servicecategorypage',
            name='spec_col_5_ar',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='servicecategorypage',
            name='spec_col_5_en',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='servicecategorypage',
            name='spec_col_5_sv',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='servicecategorypage',
            name='spec_col_6',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='servicecategorypage',
            name='spec_col_6_ar',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='servicecategorypage',
            name='spec_col_6_en',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='servicecategorypage',
            name='spec_col_6_sv',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='servicecategorypage',
            name='spec_col_7',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='servicecategorypage',
            name='spec_col_7_ar',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='servicecategorypage',
            name='spec_col_7_en',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='servicecategorypage',
            name='spec_col_7_sv',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='servicecategoryspecrow',
            name='value_5',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='servicecategoryspecrow',
            name='value_5_ar',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='servicecategoryspecrow',
            name='value_5_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='servicecategoryspecrow',
            name='value_5_sv',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='servicecategoryspecrow',
            name='value_6',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='servicecategoryspecrow',
            name='value_6_ar',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='servicecategoryspecrow',
            name='value_6_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='servicecategoryspecrow',
            name='value_6_sv',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='servicedetailpage',
            name='spec_col_5',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='servicedetailpage',
            name='spec_col_5_ar',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='servicedetailpage',
            name='spec_col_5_en',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='servicedetailpage',
            name='spec_col_5_sv',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='servicedetailpage',
            name='spec_col_6',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='servicedetailpage',
            name='spec_col_6_ar',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='servicedetailpage',
            name='spec_col_6_en',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='servicedetailpage',
            name='spec_col_6_sv',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='servicedetailpage',
            name='spec_col_7',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='servicedetailpage',
            name='spec_col_7_ar',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='servicedetailpage',
            name='spec_col_7_en',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='servicedetailpage',
            name='spec_col_7_sv',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='servicedetailspecrow',
            name='value_5',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='servicedetailspecrow',
            name='value_5_ar',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='servicedetailspecrow',
            name='value_5_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='servicedetailspecrow',
            name='value_5_sv',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='servicedetailspecrow',
            name='value_6',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='servicedetailspecrow',
            name='value_6_ar',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='servicedetailspecrow',
            name='value_6_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='servicedetailspecrow',
            name='value_6_sv',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
