# Generated by Django 4.2.28 on 2026-07-30 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def assign_customer_numbers(apps, schema_editor):
    CustomerProfile = apps.get_model("electricity", "CustomerProfile")
    for number, customer in enumerate(CustomerProfile.objects.order_by("created_at", "pk"), start=2500):
        customer.customer_number = number
        customer.save(update_fields=["customer_number"])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('electricity', '0036_servicecategorypage_spec_col_5_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('title', models.CharField(default='Invoice', max_length=160)),
                ('invoice_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_terms_days', models.PositiveSmallIntegerField(default=20)),
                ('invoice_type', models.CharField(choices=[('standard', 'Standard invoice'), ('rot', 'ROT invoice'), ('material', 'Material invoice'), ('labour', 'Labour invoice'), ('part', 'Part invoice'), ('credit', 'Credit invoice')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready to send'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('credited', 'Credited')], default='draft', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('work_address', models.CharField(blank=True, max_length=240)),
                ('currency', models.CharField(default='SEK', max_length=10)),
                ('discount_type', models.CharField(choices=[('none', 'None'), ('fixed', 'Fixed amount'), ('percent', 'Percentage')], default='none', max_length=12)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rot_enabled', models.BooleanField(default=False)),
                ('rot_percent', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('rot_personal_number', models.CharField(blank=True, max_length=40)),
                ('rot_property_designation', models.CharField(blank=True, max_length=120)),
                ('rot_brf_org_number', models.CharField(blank=True, max_length=40)),
                ('rot_apartment_number', models.CharField(blank=True, max_length=40)),
                ('customer_message', models.TextField(blank=True)),
                ('payment_instructions', models.TextField(blank=True, default='Pay to Bankgiro 5192-1302 and state the invoice number.')),
                ('internal_notes', models.TextField(blank=True)),
                ('additional_terms', models.TextField(blank=True)),
                ('rounding', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal_ex_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rot_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_inc_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation_booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='electricity.consultationbooking')),
            ],
            options={
                'ordering': ['-invoice_number'],
            },
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='customer_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='property_designation',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('labour', 'Labour'), ('material', 'Material'), ('transport', 'Transport'), ('other', 'Other')], default='labour', max_length=20)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit', models.CharField(default='fixed price', max_length=30)),
                ('unit_price_ex_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_type', models.CharField(choices=[('none', 'None'), ('fixed', 'Fixed amount'), ('percent', 'Percentage')], default='none', max_length=12)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=25, max_digits=5)),
                ('rot_eligible', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='electricity.invoice')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='electricity.customerprofile'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='electrician_booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='electricity.electricianbooking'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='on_call_booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='electricity.oncallbooking'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='service_booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='electricity.servicebooking'),
        ),
        migrations.RunPython(assign_customer_numbers, migrations.RunPython.noop),
    ]
