# Generated by Django 4.2.28 on 2026-07-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0038_move_customer_numbers_to_2500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='title',
            field=models.CharField(default='Faktura', max_length=160),
        ),
    ]
