# Generated by Django 4.2.28 on 2026-07-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0039_alter_invoice_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='part_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='part_total',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
