# Generated by Django 4.2.28 on 2026-07-30 12:31

from django.db import migrations, models


def copy_customer_emails(apps, schema_editor):
    Invoice = apps.get_model("electricity", "Invoice")
    for invoice in Invoice.objects.select_related("customer"):
        invoice.recipient_email = invoice.customer.email
        invoice.save(update_fields=["recipient_email"])


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0040_invoice_part_number_invoice_part_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.RunPython(copy_customer_emails, migrations.RunPython.noop),
    ]
